### ISSUE TITLE
[Feature] Item loading/Unloading using a forklift.

### ISSUE THREAD

**Issue by TheCactus27** [DonBruce64/MinecraftTransportSimulator#101]
Using a forklift, barrels, and crates can be removed or loaded onto a vehicle. On the forklift, the crates must be placed on a pallet, and the pallet can be placed on the ground.

**Comment by DonBruce64** [comment]
This is waaaay more immersion than I want to get into.  For starters, the fact you are required to place the crate/barrel on the ground with a pallet means that I'd have to code pallet systems.  Not to mention most users would just wrench all the crates/barrels and get them off that way rather than using a forklift.  This is a realistic feature for sure, but it's not really fit for Minecraft as a whole.
