### ISSUE TITLE
When remove the weapon from hands while firing, the bullets freeze in place.

### ISSUE THREAD

**Issue by Prophet2002** [DonBruce64/MinecraftTransportSimulator#1012]
![Скриншот 14-12-2021 121149](https://user-images.githubusercontent.com/65333989/145938723-1cb6f10e-3fa4-41ff-b9af-2b3caac44d57.jpg)

**Comment by DonBruce64** [comment]
So I know why this happens, but fixing it won't be easy.  I'm going to work on this as part of the player/entity abstraction code I need to work on, but that'll take a bit as it's part of the update schedule and can't really be pushed.  Since this is only visual, I'm going to flag it as a bug, but a non-critical on that'll take a bit of time to fix.

**Comment by DonBruce64** [comment]
Fixed in V20.5.0.
