### ISSUE TITLE
Creatures adopt player pitch and roll angle

### ISSUE THREAD

**Issue by Einsiedler98** [DonBruce64/MinecraftTransportSimulator#103]
Because it seems that we broke the issue #95 down to player characters pitch and roll angle in their seat relating to the angles of the plane and you might have to rework this mechanics anyway, I want to draw attention to another issue that might be related to this mechanics as well. 
As you can see in the pictures below, it seems that not only the player character but all creatures in the world adopt the adjusted pitch and roll angles, which make them float through the air. It's still a bit odd, because they do not tilt in place but rather move like a pendulum on a string. Note: This _only_ happens in third person view.
I guess it's also interesting to note, that this does not occur in your latest test build which disables the feature that you gave me in the OpenGL bug report.
![2019-03-13_10 33 49](https://user-images.githubusercontent.com/8685059/54269225-40172d00-457d-11e9-9370-b7bf37134078.png)
![2019-03-13_10 33 29](https://user-images.githubusercontent.com/8685059/54269226-40afc380-457d-11e9-819b-7aa805738921.png)

**Comment by DonBruce64** [comment]
Does the same behavior happen when you disable shaders, or whatever component it is that in conjunction with MTS gives you Stack Overflows?  I guess what I'm saying is: if you aren't getting the errors, are the other entities rotating like this or do they behave as normal?

**Comment by Einsiedler98** [comment]
Without a shader it is not completely gone but it also happensjust occasionally. I also strangely had the stack overflow error without a shader for the first time during this test, so it might still correlate with that OpenGL thing.

**Comment by DonBruce64** [comment]
Odd, I'd really like to pin-down if the two are related, as I'm pretty sure they are.  That code handles rotation of the player, and if Optifine and/or Shaders are prematurely ending my rotation code, it would explain why they occur in tandem.  Not only am I rotating more than the player, but when I go to end rotation I don't have anything to end, and so Optifine gets confused.

**Comment by Einsiedler98** [comment]
Okay, I guess you can still assume them to be related, since the issue was gone in your experimental build without player rotation. But I would suggest that you try to reproduce the whole OpenGL error thing on your machine to exclude other factors from beeing relevant.

**Comment by DonBruce64** [comment]
Well, the OpenGL error is one thing, but I myself have seen the behavior you are describing here. It was present in older versions of MFS, and affected the rendering of other players when you were inside planes.  The same pendulum motion would occur due to an error in rotation points, though this only affected players, and not other entities. It does, however, give me an idea as to what is going wrong with #95.

Because this is related to the rendering code I disabled, and the fact Stack Overflow errors indicate a rendering call is not being closed out and there are too many on the stack, I'm going to close and consolidate this into the other bug.  I'm nearly positive once I get that one figured out, this one will go away.  If not, we can always re-open this issue and go from there.
