### ISSUE TITLE
Make fuel pump dye-able based on color of fuel.

### ISSUE THREAD

**Issue by TheCactus27** [DonBruce64/MinecraftTransportSimulator#104]
White fuel pump for @DonBruce64's fuel pump idea https://drive.google.com/open?id=14HF_h4Sfgipo1yuUJtXeuiREGuZXMsY4

**Comment by DonBruce64** [comment]
Adding that this is for a feature enhancement that will allow the fuel pump take the color of the fuel in it for a visual representation of what is in the pump in addition to the name of the fuel on the display.

**Comment by DonBruce64** [comment]
Went to implement this enhancement and found that there is no color set for liquids like lava and water.  Additionally, it appears that most people *don't* set the color parameter for their liquids, which makes it incredibly difficult to do any color-changing operations that are independent of the texture of the liquid.  While I could do something like IE where there's a liquid level on the side of the tank, I don't really see a use for this as it would be too tiny for good measurements and look odd if I put it on the base.  Closing due to the impossibility of this task.
