### ISSUE TITLE
modifiable beacon/waypoint destination on the fly

### ISSUE THREAD

**Issue by BlazeWolf1122** [DonBruce64/MinecraftTransportSimulator#1121]
if you make a beacon named **(beacon name):1** then another named **(name, same as beacon 1 name):2**, a gauge showing beacon direction will point from beacon 1 to beacon 2

alternatively, beacons can have another field where once you go to beacon 1 you can tell it to go to beacon 2 if you've passed beacon 1

maybe these should be defined as waypoints more than beacons
![image](https://user-images.githubusercontent.com/63666200/158007945-e5ed47eb-09a9-42f9-8133-882ec1ce775b.png)

in addition, (while not required) the ability to randomize between various waypoints would benefit 
a symbol (instead of using "(or)") would be better, to make it easier to type up and (maybe) code in
![image](https://user-images.githubusercontent.com/63666200/158008195-695a3048-619c-4180-8860-c134c74d4210.png)

**Comment by DonBruce64** [comment]
Honestly, I don't really want to put more work into the beacons.  They don't have much use to players as Journeymap and other mappers exist, plus most folks don't know how to use em.  And for those that do, they're akin to real-life beacons, which since they match what the realists like, it suits them just fine.
