### ISSUE TITLE
Issue: No brake option in analog menu

### ISSUE THREAD

**Issue by vauxhallopel** [DonBruce64/MinecraftTransportSimulator#113]
Self-explanatory.
There is no brake option in the analog menu (CAR JOYSTICK).
(i am playing on a steering wheel so the gas pedal and brake aren`t connected.)
![image](https://user-images.githubusercontent.com/49477529/55867546-fd983e80-5b82-11e9-9f12-3370f34a391e.png)

**Comment by DonBruce64** [comment]
The reason the brake doesn't show up here is because the brake itself is a 0%-100% digital input in the code, and not a variable-level analog input.  That being said, I can easily write a small bit of code to check if the analog level of the brake pedal is above 25% and set the brake then.  Will get this in the V14 update for sure.

**Comment by DonBruce64** [comment]
Added in V14.0.0.
