### ISSUE TITLE
Request: Tailsitters

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#12]
Some aircraft (like the Lockheed XFV and Convair XFY) take off and land pointing straight up, and transition to level flight in the air. How hard would this be to add?

**Comment by DonBruce64** [comment]
This would require dynamic thrust.  While I *should* be able to add it, it will take quite a while to design the physics system for that, especially with planes having issues already with slowly falling to the ground due to a faulty physics system.  Helicopters are far more likely to be the short and medium term solutions to vertical takeoff.

**Comment by DonBruce64** [comment]
So what you're saying is that you want rocket engines for MTS?

**Comment by fsendventd** [comment]
No. Let me throw some links at you. This is the kind of plane I'm talking about.
 https://en.m.wikipedia.org/wiki/Convair_XFY_Pogo

**Comment by fsendventd** [comment]
And this one. https://en.m.wikipedia.org/wiki/Lockheed_XFV

**Comment by DonBruce64** [comment]
Technically that's already possible.  You'd just need to get the plane to orient itself in the upward direction upon placement and have a strong enough engine to overcome gravity.  The latter is easy, the former not so much, as your center of gravity is going to make you try to tilt downwards on takeoff and the plane won't be able to land without stalling itself.  I'd much rather do helicopters than this, but if someone makes a way for this to work, I won't stop them from implementing it in the mod.
