### ISSUE TITLE
Armor Rendering bug whit Mr Crayfishs Obfuscate mod

### ISSUE THREAD

**Issue by IvorAmlug** [DonBruce64/MinecraftTransportSimulator#1208]
Forge: 1.12.2 14.23.5.2859
Immersive Vehicles: 1.12.2 21.2.0
Obfuscate: 1.12.2 0.4.2
So Little Background information there is More mods for example Mr Crayfishs Gun mod (thats why i have Obfuscate in the first place)
And ofc some Vehicel Packs and more.
But u just need those 2 to reproduce thats why i only listed them (i tested it with just those 2)
Here is the Problem:
![2022-05-14_19 57 02](https://user-images.githubusercontent.com/38656481/168443331-15bceafe-c6ea-4b19-9e16-1f1740442c20.png)
![2022-05-14_19 57 06](https://user-images.githubusercontent.com/38656481/168443346-7b1a878c-4774-476e-af8c-bde41ac3c5a8.png)
![2022-05-14_19 57 09](https://user-images.githubusercontent.com/38656481/168443347-3e7260d3-aaeb-4ea0-8ca0-0e465776fb62.png)
As you might see the armor dosnt get rendered correctly this affects mod armors too (Ender Io, Pams Harvest craft etc) eccept 3d armors like Construcs Armory.
Idk if this on your side to fix but this was my first guess where to post it if there is nothing u can do about it ill post it on Obfuscate Github.

**Comment by DonBruce64** [comment]
This can be fixed if you turn off playerTweaks.  playerTweaks does some rendering overrides to make player models render all nice in vehicles, as MC doesn't allow for rotating in roll and moving player hands by default.  It is not a bug in those other mods as IV is doing things with the player model they don't expect.  But I can't do animations any other way with the existing system.  So this bug will stay open forever.

Or until Forge devs make some useful events to not need this instead of spending time in yet another Forge code re-write....
