### ISSUE TITLE
Making wheels possible to drive in water

### ISSUE THREAD

**Issue by TheOddlySeagull** [DonBruce64/MinecraftTransportSimulator#121]
That probably sounds weird, but it is actually a irl thing.
As you know, I tried an amphibious car, though it is impossible to drive in water with the wheels. Why not make wheels drive in water? Like in that vehicle that is btw another planned Trin model:
https://media.discordapp.net/attachments/568079606410641418/568362392287969300/sherp-atv.gif
This car wheel feature can be automatically applied to cars that have maybe over 1.5 grip?

**Comment by DonBruce64** [comment]
I can't make wheels drive in water simply because wheels have no grip in liquids as liquids don't have any hardness like regular blocks.  Even pontoons don't have any grip: it's the propellers on the plane that power the vehicle.  I could see about allowing for boat engines to be placed on cars, but that's complicated as it would be two engines for a car which they don't support.  You can still do a hovercraft of sorts if you really want an amphibious vehicle, though.  I may revisit this after boats, but don't expect it any time soon, if at all.
