### ISSUE TITLE
Why the Ils input has been removed in new version of IV(mts).

### ISSUE THREAD

**Issue by ChengxiX** [DonBruce64/MinecraftTransportSimulator#1214]
![image](https://user-images.githubusercontent.com/61776833/169441567-3eaa7cb6-dfd6-4f07-9720-5fadcc507b0a.png)
Why the Ils input has been removed in new version of IV(mts) 20.x. It works well in 19.x. And the map on the right upper side also disappear in 20.x
I'm sure that it's about Iv itself instead of other packs

**Comment by DonBruce64** [comment]
V20 is obsolete.  Please use V21.  This version has a config to re-enable those.

**Comment by ChengxiX** [comment]
I do use Iv v21.2.0

**Comment by ChengxiX** [comment]
I  understand, thank you

**Comment by ChengxiX** [comment]
Thank you. How the config file work in server? Do the config[config, configclient and treanslation] in server have a higher priority?

**Comment by DonBruce64** [comment]
So each of those config files do different things.
config: Has configs that are shared between server and client, and should be the same on both or you will get funny stuff.
configClient: Only used on the client, and doesn't do any server stuff.  This is mainly what stores the controls and rendering options you see with the P-key config menu.
translation: Language files used for displaying text to the player.  Really only for the client, but due to some wonky code they are looked at by the server.  Though this doesn't actually change anything so they don't have to be synced.

For your config, you want to change the value in the main config file and make sure it's synced to all clients.  The reason for that was so server operators can make their choice as to whether or not all planes have ILS, or just fancy planes.
