### ISSUE TITLE
Most vehicles don't drive after last update

### ISSUE THREAD

**Issue by 1Pawelgo** [DonBruce64/MinecraftTransportSimulator#122]
Hello,
I'm running a private sponge forge role-play server, and after updating your mod from 13.1.0 to 14.0.0 vehicles from Non-updated packs don't drive (only cars from official pack are working). We can interact with cars, mount/unmount parts, fill fuel, run engine, but engine doesn't drive on any gear. There are no errors/warnings in console log when using mod.

Mod/Plugin list:
http://modlister.com/server/mc.pawelgo.us

Server startup log:
https://pastebin.com/FgX7gmv6

**Comment by DonBruce64** [comment]
This bug exists due to a small change made to car gearing systems in V14.  I mentioned this to the pack authors that this change was coming, but it appears most of them haven't updated their packs yet.  I'll mention this to them again, as all they need to do is add a single variable to the JSON of their vehicles.

Should you wish to do this yourself to manually patch them you can add `"axleRatio" : 3.55,` to the `"car"` section of the JSON.  That'll hold till they decide what to put in themselves.

**Comment by PearlCGDoesYT** [comment]
That explains my issue

**Comment by 1Pawelgo** [comment]
Thank you for response. I have patched all packs myself, as you suggested, and now cars are working properly.

**Comment by DonBruce64** [comment]
Good to hear.  I'm going to leave this ticket open until the packs update.  So far the ones that have updated are:
Dr. Professor Luigi's packs (Blackthorne, UNU)
The Oddly Seagull's packs (Trin)
Adam RK's Pack

**Comment by DonBruce64** [comment]
Closing as Blue20Boy17 has said he is abandoning his pack, therefore all currently-maintained packs are updated.
