### ISSUE TITLE
[Incompatible] MoBends 

### ISSUE THREAD

**Issue by Kadwinflo** [DonBruce64/MinecraftTransportSimulator#1240]
the MoBends animations are overwriting MTS animations and some are messed-up
Mobends id : "modid": "mobends"

**Comment by DonBruce64** [comment]
So, I can't fix the MoBends overwriting MTS's animations.  MoBends replaces the player model with their own style, so when I go to modify the things I normally do in the model for MTS, it doesn't work because it's a MoBends model.  The best I can do is just turn playerTweaks off if that mod is installed.

**Comment by DonBruce64** [comment]
Fixed in V21.3.0.
