### ISSUE TITLE
Not working camera animations

### ISSUE THREAD

**Issue by Wartich** [DonBruce64/MinecraftTransportSimulator#1244]
When i add 
"cameraObjects": [
	  {
            "animationType": "translation",
            "variable": "seat_rider_pitch_1",
            "centerPoint": [0.0,0.836645,-1.05786],
            "axis": [0.0,0.0,-0.5]
          }
to cannon json, camera does not follow player view, but instead moves with cannon.
if this line is added to json of vehicle, that carries this cannon it works fine

**Comment by DonBruce64** [comment]
If you reference a part in a JSON, then the system looks for the part in the JSON you referenced.  Since you are referencing the seat in the cannon JSON, it looks for the seat on the cannon.  But, from what you're saying, the seat is on the vehicle.  So it can't find it on the cannon.  This is expected behavior.
