### ISSUE TITLE
[Bug] Guns all fire at the same time together

### ISSUE THREAD

**Issue by LauraDarkez** [DonBruce64/MinecraftTransportSimulator#1275]
![image](https://user-images.githubusercontent.com/53153740/182046223-3eb23f6b-c3a3-4838-87d7-fcfe4ea3e268.png)

https://user-images.githubusercontent.com/53153740/182046232-7b581a36-52dc-4e1c-80d3-2d426ee02c2a.mp4

**Comment by boot2big** [comment]
Perhaps linkedParts implementation for this, as I'd noticed it when putting mounted vehicle guns on both sides of a car, so I'd assumed it was an intentional feature
This way guns like vid related or turrets you would expect to only fire from one side/gun at a time can coexist with simultaneously firing machine guns or rockets

**Comment by DonBruce64** [comment]
linkedParts is a beta thing, and tells IV what guns are linked to what seat.  That wouldn't be a release bug which this is.  For this, the guns should be firing in sequence since they aren't marked as fireSolo.  Flagging this as an overhaul thing though since I change that logic in the part linking overhaul.

**Comment by DonBruce64** [comment]
Fixed in V22.0.0
