### ISSUE TITLE
[ENHANCEMENT] "Random" animation variable (java math.random)

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1287]
For anything from varying pitches to playing different soundfiles. Would probably make use of clampMin/clampMax as its range of operation, otherwise maybe a predefined range, though I would need other PAs to weigh in on what said hardcoded value should be if it can't be custom defined

**Comment by DonBruce64** [comment]
So you don't need to make use of the clamps.  Just scale the axis.  Math.random() returns a value 0->1, so you can use that and scale it with an axis to make it whatever you wish it to be.

Just be aware that this value will be random every time it's used, so if you use it in an animation, it'll spazz out.

I'm going to leave this one as a PR, since it's a one-line code addition in the common entity file that both vehicles and blocks use as a `case` in the `switch` statement where stuff like sunlight, rain, and the like are returned.

**Comment by boot2big** [comment]
https://github.com/DonBruce64/MinecraftTransportSimulator/pull/1293
I spent more time finagling with github to get the PR set up than it took to write the code in notepad

**Comment by DonBruce64** [comment]
Implemented in V22.0.0
