### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by Workersteve** [DonBruce64/MinecraftTransportSimulator#1301]
Hello
I said this suggestion before but i think you didnt read this...

1.Engine and the battery of vehicles get older.
For example the battery max durability get less after a long time and you must use "battery changer" tool to fix vehicles battery.
Even engine get weaker and it can be overheat easier and even get lower speed. Old engines some times turn off automatic. If the engine get so old it can be stalled.

2. Temperature effect at start time and battery power (I mean for example in snow or maybe high places that the weather is cold the battery of cars work weaker and take more time to start.)
I wish you like my ideas. I think immersive vehicles would be really more fun with this mods!
I really like your mods , please continue them!

**Comment by DonBruce64** [comment]
Not going to happen.  We already have enough issues with folks not understanding what a dead battery means.  Having one that gets weaker and has less power over time will just add to the confusion.  Engines right now do get weaker with age, so that's already a feature.  Even to the stalling.  So that tells me that you haven't gotten deep into the mod to see the same features you are requesting.
