### ISSUE TITLE
[Suggestion] (im sorry if you dont like)

### ISSUE THREAD

**Issue by Workersteve** [DonBruce64/MinecraftTransportSimulator#1309]
Hello again , i have some another ideas wish you like.
1. Immersive vehicles is most onroad and only speed is important , but if you do a offroad update i think this mod will be more cool
For example cars stuck in wet dirt and ice and maybe sand or whatever you like. (My mean of stucking is , the wheels are turning but no more speed and even losing speed and maybe a bit sinking in snow or etc , if you enter sand slow you will stuck)
Trucks and offroad vehicles or maybe their tire size will be important 
I know minecraft doesnt have alot snow but many players are using serene seasons.
Or maybe chain for wheels if you want
2. Sometimes our car will drop in water and we have no tool to pick it and cars dont work at 1 block water , so what to do? I think adding something that we use it to pull the car with the animal (for example donkey or horse) i know we are not at 17 century but it will be cool... but if you dont like it , then you can forget my idea...
3. Nitrogeon is the heart of drag of we dont have it. I think adding nitrogeon will be cool , and even you can add something that shows the pressure of nitrogeon in car.
4. I know i said something like this before but add stall chance (I mean engine stall) (and add it in config file) , the engine with higher than 500 hours or whatever you want will have a chance for stalling (turn off) like real life , its not something very confusing and i think its simple to add , but do whatever its right.

**Comment by Workersteve** [comment]
I have another idea!
Many players use this mod for rp servers and they have roads with limited speed signs but this is hard to calculate their speed. I think its better to add a kind of block in roads that when somebody passes it , it calculates his/her speed and shows us.

**Comment by boot2big** [comment]
1 and 3 are entirely packard, you will have to reach out to your local pack author for these. (And I'd _love_ to see you convince any of us to nerf our vehicles to hell and back when they're crawling through sand or dirt...)
2, You have a WRENCH!!! USE IT!!!  And if your local sysadmin disabled picking up vehicles using wrenches, go bug them to pull your vehicle out of the water or get ready to use a lot of sponges and buckets...
4 is already implemented? It happens 250 hours quicker, but engines _do_ in fact sputter out once you abuse them to hell and back or drive them for... 250 ingame hours.

5, Have... your players install a speedometer instrument into their car? Or if you mean a radar/laser speed gun, that would also be packard since it'd require a pack author to make a radar gun model.

**Comment by Workersteve** [comment]
For 1 maybe ok but for 3 we can add a nitrogeon capsule and click it on cars and fill their nitrogeon to 100% (maybe 2 instruments for nitro pressure and for how much we have nitrogeon) can be actived by holding i
For 2 i said this is just some thing fun 😂 and maybe you wont like it but i said we dont have tools but anyway you are right
For 4 if we have this feature please add it in config
For 5 i mean two placeable block that when someone passes between them it will show the speed of him/her
(But laser gun is good idea too)

**Comment by DonBruce64** [comment]
Git is not a place for random suggestions.  It is for bugs, and confirmed requests from pack authors for new content.  Please take suggestions like these to the Discord.

**Comment by Workersteve** [comment]
Ok thanks.
