### ISSUE TITLE
Animations skipping if previously blocked by visibility or inhibitors

### ISSUE THREAD

**Issue by Ooferine** [DonBruce64/MinecraftTransportSimulator#1313]
![image](https://user-images.githubusercontent.com/45642968/188151542-389d61f2-3c00-4869-9af2-9cd30521ac05.png)

**Comment by DonBruce64** [comment]
So, it turns out this is per-operations, and will remain as so.  Basically, blocking animations from operating with a visibility block prevents them from seeing variable state-changes.  And as such, they don't do animation duration properly.  This can be avoided by either doing the visibility block last, or scaling the initial object so small you can't see it in cases with applyAfter where you can't invert the order of operations and the master object has to come first.
