### ISSUE TITLE
[enhancement] Auto pitch trim

### ISSUE THREAD

**Issue by Ilya-torshov** [DonBruce64/MinecraftTransportSimulator#1319]
I beg of you to add this feature. Planes are almost completely unusable because of the pitch variations, having to poen the panel to adjust it and spam click a button every time you do anything makes flying more uncomfortable than anything else. Futhermore the "autopilot" feature seems to be broken and does nothing but crash your plane

**Comment by Ilya-torshov** [comment]
Auto Pitch trim will basicly make it so the plane will always be at the input pitch, not having to be adjusted constantly by the player to account for speed and other variables that make it so. For this feature I have two suggestions
1. Add a "hasAutomaticPitchTrim": True boolean for planes so planes that have this feature in real life can have it (most modern fighters, airliners, etc)
2. Add an "automaticPitchTrim" config boolean for the feature to apply universally as a difficulty setting, simmilar to the simple driving stuff in game already

**Comment by DonBruce64** [comment]
TBH, this sounds more like an advanced autopilot.  Please make another ticket for the actual autopilot however, as that is most assuredly broken.  Will evaluate this feature seperately.

**Comment by DonBruce64** [comment]
After further thought, I can't see adding this without allowing for a comprehensive autopilot system.  And that would require the custom panel system Turbo was working on.  Maybe sometime in the future I will work on this.  As to current issues with planes: if you get into a phughoid cycle, it's because you're going too fast for the plane.  Either reduce throttle, or reduce wing area.  The Trimotor is horrid to fly at max throttle with the OCP engines as it's not designed for those.  But the MC-172 and the P11 with their engines?  Glide super smooth.
