### ISSUE TITLE
[Suggestion] Aircraft related features

### ISSUE THREAD

**Issue by SYDoukou** [DonBruce64/MinecraftTransportSimulator#133]
This is just a suggestion, feel free to close this.
1. Smooth animated flaps
2. Visualize airbrakes
3. Visualize jet engine reverse thrust

**Comment by DonBruce64** [comment]
Number 3 is already a thing.  There's already a rotationVariable for it.  As to number 2, I'm going to lump reverse thrust into airbrakes, as having yet another keybind would make the joystick GUI overflow and doesn't add too much to aircraft systems.  Basically, if players want to have airbrakes on their planes, they should be linked to reverse thrust as actual airbraking won't be implemented due to the complexity.

And as to smooth flaps, that's do-able for sure.  Will be restricting this ticket to that item.

**Comment by DonBruce64** [comment]
Addressed in V14.2.0.
