### ISSUE TITLE
[Enhancement] duration/smoothing for analogue variables

### ISSUE THREAD

**Issue by Ilya-torshov** [DonBruce64/MinecraftTransportSimulator#1374]
As to our conversation in garage

**Comment by DonBruce64** [comment]
I'm canning this ticket.  Not because it's super hard (though it is complex), but the only thing I see this being used for is connecting an increment variable on a lever to something that moves with that lever, to keep it from just jerking into place.  In this case, what you're really wanting is lever-activated smooth movement.  Like a forklift raising a pallet, or a bucket truck, or the rear of a food truck in a certain GAP.  In all cases, Variable Modifiers do this far better, as you can connect a hitbox "button" to an up or down command, and even set limits, to get the instant-motion.  Or, you can use the increment, and use it as a "move-to" sort of VM where your thingy slowly moves to the position requested (like a ladder truck or tank turret).  In summary: VMs give more granular control of analog movement, and don't incur the complexities of easing code to have a double-variable situation that can easily lead to de-synced animations.
