### ISSUE TITLE
[enhancement] Placeholder model for when model is missing

### ISSUE THREAD

**Issue by Ilya-torshov** [DonBruce64/MinecraftTransportSimulator#1387]
Will be displayed in the event of no .obj file being present instead of crashing the game
Useful for development, and for not locking players out of their worlds if a PA made a mistake

[noobj.zip](https://github.com/DonBruce64/MinecraftTransportSimulator/files/9840570/noobj.zip)

**Comment by boot2big** [comment]
Mixed feelings on this one, I feel like having MTS/MC crash in the event of a missing model would result in more attention to the issue, resulting in a quicker fix. On the other hand this would definitely be more convenient in the event that a fix _isn't_ coming for one reason or another. Ultimately up to Don though

**Comment by Ilya-torshov** [comment]
If the big purple ERROR doesn't get the attention of a PA I don't believe a crash will either

**Comment by Ilya-torshov** [comment]
It's also just very annoying having to re-start the game because you erroniously named one of 4 new jsons

**Comment by boot2big** [comment]
The idea isn't that the PA would be getting attention to the issue ingame, the idea is all the angry people complaining to the packdev and others, resulting in said others complaining to the packdev will get their attention.

Plus, you're gonna hafta restart the game to rename those jsons at some point anyways. Better to at least get the issue out of the way.

Maybe this should be left to a configuration option so that by default it crashes the game, but in the event that somehow a pack erroneously has a missing OBJ, users aren't _locked out_ of their world by any means.

**Comment by LauraDarkez** [comment]
i think this feature should be an option for pack authors but the event where if a pack author releases a pack with this type of error seems highly unlikely. a beta perhaps might have this issue but an official release should never have an obj that doesnt align with the json in some way

**Comment by DonBruce64** [comment]
I won't do a config, but I can see about making the system make a rando model and texture if it gets a null.  I don't like it as PAs shouldn't drop new content without at least *placing* their things into the world to test them and ensure they have models, but since it's a PA asking to make his life easier, I can jive to that.

**Comment by boot2big** [comment]
I personally still partially disagree with this suggestion as a whole, but this sounds like a good solution.

**Comment by DonBruce64** [comment]
I mean, devMode exists to make a workflow that will still run with clobbered JSONs, so I can't complain too much about this.  If it's hard to do though, I'll wontdo it.  An actual model, however, that's not just invisible, would be ideal for this, @Ilya-torshov

**Comment by DonBruce64** [comment]
Looked into this.  Changing it will be very tough, as it'll require changing the I/O loading code deep in the model parsers and changing logging information.  Honestly, since I've only seen this be a user-issue in the no-flat-wheel-model days that are over due to it being opt-in, I don't see this as a bug that'll hurt the end-user, so not one that I can see myself dedicating my time to.
