### ISSUE TITLE
[bug] Rudder does not work on airship

### ISSUE THREAD

**Issue by Ilya-torshov** [DonBruce64/MinecraftTransportSimulator#1397]
Tried every airship currently in game as well as messing around with my indev one

**Comment by DonBruce64** [comment]
Did you try the ailerons?

**Comment by Ilya-torshov** [comment]
Yeah, rudder keys will trigger animations (ailerons don't) but neither set seem to do anything at all

**Comment by Ilya-torshov** [comment]
It is to note that once I remove the isBlimp thingy it works perfectly fine, but ofc I don't have the gearbox reversers or pbrake anchor which is kinda a must

**Comment by DonBruce64** [comment]
Yeah, I need to fix that.  The idea was that I'd shunt the aileron keys to the rudder controls to allow blimps to be "driven" with the WASD keys like planes, since they use rudder to turn rather than aileron.  Basically a @boot2big special.  I probably borked it up when I split the input and output variables and never checked since I had no blimps to check with.  UNU blimps were super borked at that time.

**Comment by boot2big** [comment]
Oooough, I ain't touching that blimp stuff with a stick. I just figured I was doing my blimp stuff wrong since my "blimp" vehicle doesn't have any rudders anyways, so I had just resorted to moving the motors.

**Comment by DonBruce64** [comment]
@boot2big No no, I mean you try and steer planes like blimps!

**Comment by boot2big** [comment]
![image](https://user-images.githubusercontent.com/53581325/199414647-60282392-8885-4ca0-9553-615383fac268.png)

**Comment by DonBruce64** [comment]
Fixed in 22.4.0.
