### ISSUE TITLE
More options for handling tuning

### ISSUE THREAD

**Issue by Karakownia** [DonBruce64/MinecraftTransportSimulator#144]
Hello,
I've been searching vechicle .json files to find something for determinig vechicle handling features like turning ability or something to define vechicle oversteer/understeer... But I found nothing useful... 
That's first case, second one is about massive oversteer which occurs at more than 100 KPH. I know, not everybody wants such speed in minecraft, but 2.5 L Twin Turbo Nissan GTR with Vmax around 75 KPH seems like a little joke to me... And I think about making something like that for this mod...

**Comment by fsendventd** [comment]
~~bleh, GTRs are overrated~~
But in all seriousness, a lot of those things are defined in the wheel JSON in relation to grip. Also, as to the speed, that's because of the speed factor. MC doesn't like fast vehicles, so we adjust the physics calculations to slow them down. The default is 0.35, which means vehicles only move at 0.35 of their actual speed.

**Comment by DonBruce64** [comment]
Fsend is right.  The speedFactor is what is limiting the vehicle to 75KPH.  That's because MC doesn't like things moving at over 120KPH, which is 2 chunks a second.  You try making a server generate that many chunks that fast and it'll have a bad time.

As to the steering, that is indeed relegated to the wheel JSON, as the tires you have directly impacts the ability of your car to steer at those higher speeds.  When you have the car maxed-out at 75KPH with the default speedFactor of 0.35, you're actually going about 215KPH in the internal physics code.  Not much steering response to be had at those speeds.  If you truly want realistic physics for fast vehicles, you'll need to set your speedFactor to 1.0.  Just don't expect to run at 30FPS and 20TPS if you do so...
