### ISSUE TITLE
[Bug] Cannot add any engine to waywardcraft planes.

### ISSUE THREAD

**Issue by ziegmaan** [DonBruce64/MinecraftTransportSimulator#1443]
Problem: In piston engine planes of waywardcraft pack when you use the scanner in the engine place no engine is suitable for use, and you cannot place any engine in the engine bay (Jet engine planes work).
Example:
https://cdn.discordapp.com/attachments/902698390033424474/1050237052567965696/image.png

Packs Included:
- Immersive Vehicles (MTS/IV) - Official Content Pack
MTS_Official_Pack_V20.jar

- UNU Parts Pack [MTS]
UNU Parts Pack [MTS] 1.12.2-21.3.0-5.1.4.jar

- Waywardcraft (Immersive Vehicles Pack)
Wayward_pack_V03.jar

**Comment by DonBruce64** [comment]
You're using a horridly-outdated Official Pack.  Does this issue persist with the latest one?

As to UNU, they refuse to follow conventional aircraft standards where you mount the propeller to the engine, so the Waywardcraft pack doesn't support their engines, since you'd not be able to do anything with them since they don't allow you to put propellers on them.
