### ISSUE TITLE
Ground vehicles crash way too easily

### ISSUE THREAD

**Issue by happysmash27** [DonBruce64/MinecraftTransportSimulator#147]
I was driving up a tiny hill and died in a car crash... perhaps because of the slightly uneven surface I was driving up? Once I put a single dirt block in front of a vehicle and it crashed. Isn't this a bit much? 

I would comment in https://github.com/DonBruce64/MinecraftTransportSimulator/issues/83, but it is limited to collaborators.

**Comment by DonBruce64** [comment]
You are correct about that being too sensitive.  The next update won't come out until that is addressed, however long that may take.  #83 was designed to be a catch-all for the bugs related to ground physics, so rather than make it long by allowing people to comment on it, I keep each issue separate and roll them into that issue to better collect the problems associated with the system.  I'm going to close your issue here, but link it to that main thread.  Feel free to comment here should you desire.
