### ISSUE TITLE
[BUG/OS] Roll/yaw/pitch force modifiers are non-functional, haven't been for ages

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1499]
Unsure if by now they're supposed to be considered implemented, or unimplemented. I can't seem to find them on the wiki, and yet I recall seeing them somewhere in the jsondefs classes, as well as maybe one of the vehicle entity classes.

If nothing else it'd be helpful to know if they've been canned or not, or if they're going to be fixed at some point.

AFAIK this _should_ be outsourced to BlazeWolf1122 as it was his PR.

**Comment by boot2big** [comment]
P.S Don, if you see a blank notification in your inbox, is my fault. Am sleepy.

**Comment by DonBruce64** [comment]
These were part of a PR maybe?  I know Blaze had talked about them, but I know for a fact I myself never put them into the code.  The reason being that the physics system has a lot of moving parts (ground collision, braking, steering, drag, etc.), so trying to directly modify the force output of that complex function can lead to Bad Stuff.  The better option is either modifying one of those inputs, which you can do for most of them though VMs, or fix the areas where the physics doesn't work right.

Closing this as invalid since it's not for anything that was done, and not for anything I will do.

And yes, I did see a blank inbox!
