### ISSUE TITLE
[Suggestion] (probably for later) Door opening without needing the parking brake.

### ISSUE THREAD

**Issue by TheCactus27** [DonBruce64/MinecraftTransportSimulator#152]
Rather than opening with the parking brake, doors would be able to be opened with a key combination (MOD+ number.) This would allow for up to 10 openable doors which is more than enough for a reasonable car, truck, or plane. The door number would be defined in the json.

**Comment by DonBruce64** [comment]
This is indeed for later, however it is something that's already on the docket under #21.  That there is designed to allow doors to have their own hitboxes that will allow them to be opened, and the seat automatically entered once they are open.  The idea being that you'd click the door and it would open, you'd sit inside, and then the door would automatically close.  Ground physics come first, however.  As do boat physics due to popular demand.  This may come third, or fourth if helis take off.  Pun intended.
