### ISSUE TITLE
[Bug] Beacons missing text fields

### ISSUE THREAD

**Issue by LauraDarkez** [DonBruce64/MinecraftTransportSimulator#1524]
no text field = no working beacon

**Comment by gyrohero** [comment]
It looks like the issue is in GUITextEditor.java.

LegacyCompatSystem.java adds fields for name, glideslope, and bearing to the beacon's definition. However, I don't see anywhere in GUITextEditor.java (which deals with creating GUIs for things like signs and beacons) where a beacon's definition would be referenced in order to add those fields to the GUI.

**Comment by DonBruce64** [comment]
Fixed in V22.7.0.

**Comment by CSdiscoveries** [comment]
Having the same issue

**Comment by DonBruce64** [comment]
Now how might you be having this issue when you can't open the beacon GUI via #1814 ?

**Comment by CSdiscoveries** [comment]
that... is the issue. There's no text field, no HUD, nothing.
