### ISSUE TITLE
Feature Request: Weather Affects Planes

### ISSUE THREAD

**Issue by FFXG** [DonBruce64/MinecraftTransportSimulator#156]
Cool idea that could be complicated though (dont know alot about modding) maybe planes could be more difficult to fly during rainy weather and even more difficult during thunderstorms. Maybe cars and planes could slip a bit when on the ground as though runway is wet and maybe brakes would work poorly (for when its raining or storming). I was also thinking during storms planes would get hit with gusts of wind or have turbulence of some sort. I just thought this would make the mod more realistic. Also a bit of a stretch and i dont think this will be implemented if you guys add storm physics in a future update but maybe integration with weather2 but i bet it would be way too much work to add (https://coros.us/mods/weather2) Thanks for reading!

**Comment by DonBruce64** [comment]
You kind-of expected this, but integration with the weather mod is not going to happen.  IV's code is generic to the point it's nearly identical for 1.10.2, 1.11.2, and 1.12.2.  This makes integration with other mods that don't have an API nearly impossible.  If the weather mod can push flying entities, then it should work out of the box with planes, but that's about as much interaction as you will.

Turbulence was discussed way back in the MFS days, and was decided against due to the randomness of the plane movement being more of a pain than a feature.  One thing I heard over and over was, "I've played GTAV, and the plane turbulence sucks."

The one thing that I may actually implement is the slipping of vehicles during rain.  The problem becomes how to detect if it is raining on the block that the wheel is on.  I'm not sure how rain works code-wise, so I may or may not be able to know if a block can be rained on.  Will have to get back to you on this after I have time to look into the code.

**Comment by DonBruce64** [comment]
Implemented in 15.1.0.  Friction is now far worse in the rain.  Better equip a propeller with reverse thrust!
