### ISSUE TITLE
Suspension system for ground devices

### ISSUE THREAD

**Issue by ManuelSollberger** [DonBruce64/MinecraftTransportSimulator#157]
※This is related to issue #83 

My thoughts on what you could do to improve the hill climbing physics is adding a suspension system to ground devices. I could think of two ways of implementing such a feature:

- Implement a hard-coded suspension that makes a vehicle aim the pivot of the ground device at a certain speed (instead of being statically attached to it), maybe even with a configurable stiffness value (quick solution)
or
- Add a suspension as a new vehicle part that can be put inbetween a ground device and the vehicle, so it could be optional for a player to add one or not. This would allow for different kinds of suspension, each with individual stiffness properties for different kinds of applications (long-term solution)

But remember, these are just my ideas of how it might be done. Maybe you already found another great way to improve the hill climbing abilities of vehicles. In any way, I'm looking forward to see how you are going to implement it. Looking at the code, one can see that you know what you are doing, as this is truly an impressive mod!

**Comment by DonBruce64** [comment]
I made a decision early last month that the next update would fix the poor ground physics.  I also made the decision that no other updates would come out until that update did.  That has turned out to be a blessing and a curse, in that I'm getting some help from other people with the trigonometry required to do the rotation of the vehicle (which I'm not good at whatsoever), but it basically has put a stop on development pending their responses.

As to what you said: neither of those systems will be implemented.  For starters, parts don't move, so having a suspension part would just add another non-movable part.  In general, suspension isn't really something IV was ever designed for, and would be hard to implement, even if the ground physics were working correctly.  While you can put a spring onto vehicles in real-life, coding such a system is a totally different matter.  If you care to try your hands at coding it, though, I'll be happy to make it a feature!
