### ISSUE TITLE
[BUG?] Something to do with Rotors and autorotation... and throttle.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1594]
https://user-images.githubusercontent.com/53581325/230483478-b8464afc-7082-4ea0-bb28-6168d88737ae.mp4

https://user-images.githubusercontent.com/53581325/230483618-b97a2a85-877a-4f0b-a7ae-a36fba120b25.mp4

That title is the best way I can describe it. Notice the meme hud that has a helpful throttle indicator, wasn't aware of any other instruments that specifically displayed the throttle...
However the throttle seems to have a say in this bug, sometimes there's a sweet spot on the throttle that really does it and other times it just requires you to turn the throttle all the way down to do it.

**Comment by SnailPerson** [comment]
I had this happen too, specifically with the bell47.
Sometimes, when i got out of the vehicle, the rotor would start to spin exponentially faster until the audio cuts out and the blur plane disappears. the copter would usually start flying off by itself without being fueled.
The only way to stop it was to get into the copter again, which would return the rotors RPM to a normal state.

**Comment by DonBruce64** [comment]
This is due to the rotor pitch being high and the blades spinning faster as you fall down, but they cause more up-lift than they stop, and there's no "brake" on them like planes, so you end up with super fast spinning blades that make you fly up.... unless throttle is low enough to make for a negative pitch angle.  Might be a @gyrohero fix, might not.

**Comment by DonBruce64** [comment]
Addressed in 22.9.0.
