### ISSUE TITLE
Server Incompatibility after 22.8.0

### ISSUE THREAD

**Issue by Tampastrike** [DonBruce64/MinecraftTransportSimulator#1595]
I run a small server running on 1.16.5 for some buddies and after updating this mod and this mod alone, the server was unable to be connected to. Server files updated and the server started and ran, however no one was able to connect. Server list in Minecraft main menu showed server was online with good connection, however red "X" under ping meter stating incompatible FML list. After attempting to connect no specific error messages are given. Running UNU and official content packs. Reverted to 22.7.0 client and server side with no connection issues. Also worth noting issue #1580 is also present.

**Comment by DonBruce64** [comment]
This implies that your don't have the same mods on the client as the server.  The X and Forge mod incompatibility list is nothing I can do about, as it's Forge making those decisions, not anything IV is doing.  If you're sure about this, please join the Discord and we can debug it, but I'm pretty sure it's because different mods are installed.
