### ISSUE TITLE
[Bug] Drills break bedrock

### ISSUE THREAD

**Issue by LauraDarkez** [DonBruce64/MinecraftTransportSimulator#1596]
plain and simple

**Comment by boot2big** [comment]
Wasn't worth reporting before but they also happen to break fire...

**Comment by boot2big** [comment]
Uh-oh. So, I've been testing and I found a few blocks that are also breakable, that probably shouldn't be (and are a lot more serious than fire)

Barrier blocks
Command blocks
Structure Void/Loader

Granted, you won't usually find this in a standard survival gameplay setting, and most other sorts of maps/servers that make use of barriers or command blocks will usually be the sort of server with enough critical thinking to go, "Hmmm, but do our players REALLY need a tool capable of digging entire holes through the world?"

**Comment by LauraDarkez** [comment]
doesnt matter. if they arent meant to be broken, they shouldnt be broken by the drill. barrier blocks especially. command blocks im not sure about, and ive never used structure blocks

**Comment by boot2big** [comment]
Generally structure blocks aren't supposed to stick around anyways since they're used either to load in other structures on the fly, or to save/load structures manually, but that's still among the list of blocks you probably wouldn't want anyone to be able to mine and keep for themselves.

Command blocks are another thing, by default you can't just right click them to do nasty stuff if you're in survival _or_ you're not a server operator, but anyone with enough ingenuity to use a vehicle drill instead of a pickaxe to collect one will certainly find some obscure way to inject NBT into the block manually for redstone-triggering purposes. (I would know, cause I know how to do that!! 😃)

**Comment by LauraDarkez** [comment]
in that case, yeah drills shouldnt be able to break those either

**Comment by DonBruce64** [comment]
Addressed in 22.9.0.
