### ISSUE TITLE
Vehicle spawn bug at duplication

### ISSUE THREAD

**Issue by MaxifeuxG** [DonBruce64/MinecraftTransportSimulator#168]
**Describe the bug**
my bug appears when I duplicate a vehicle in items and that I want to ask it he asks himself a faith after the items and bug

**To Reproduce**
Steps to reproduce the behaviour:
1. creates a wheel and accessory vehicle
2. break it with the wrench
3. duplicate the vehicle item
4. try to ask him more faith

**Versions (please complete the following information)**
 - Forge: Forge 1.12.2 v14.23.5.2838
 - Mod: Immersive Vehicles-1.12.2-14.3.1.jar
 - Pack: MTS_Official_Pack_V11.jar

**Additional context**
Logs [gist]--> https://gist.github.com/MaxifeuxG/b852f3bae2aec28c90b77602e6062ebb

**Comment by TheOddlySeagull** [comment]
Ok, first of all, happy to see a great bug report with all needed data in a clear way.
Now the bug, I don’t guarantee it is the issue, but I think it is due to car UUID, as taking built cars also saves the key data, wich is linked to entity UUID, and minecraft won’t allow 2 entities have the same UUID. In other words, you can’t duplicate cars as minecraft won’t let you do it with the mechanic MTS uses. This is just an idea, needs to be confirmed

**Comment by DonBruce64** [comment]
I could have swore this was a bug I that I had seen and patched before, but I can confirm I am seeing it on my dev version right now.  Will fix.

**Comment by DonBruce64** [comment]
Corrected in V15.0.0.
