### ISSUE TITLE
Request: Turboprops

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#17]
Self-explanatory. Jet engine with propeller attached to it.

**Comment by DonBruce64** [comment]
Need a bit more explanation as to how these differ from regular props.  They don't provide thrust through the engine from what I can tell, so they're still a propeller-based engine, which is what the current engines are.

**Comment by fsendventd** [comment]
Well, *some* turboprops can provide a bit of thrust from the engine. And there are two types. One has a gearbox connected to the intake fan. The other one has a turbine connected to the exhaust (like a turbo in a car). Only the first type can provide power using the exhaust, the second draws too much energy from it for the prop. They differ because they're better at driving *huge*, high pitch props at low RPM, as opposed to piston engines, which are better at driving smaller/lower pitch props at high RPM. Torque vs horsepower, essentially. And turboprops can actually be more efficient...

**Comment by DonBruce64** [comment]
Hrm.  I'll consider it as I can see needing the power, but seeing as how we currently have very few people modding planes and even fewer needing turboprops, I'm putting it on the backburner.

**Comment by fsendventd** [comment]
Well, you'll be "glad" to hear I'm considering doing a turboprop as the next plane I do.

**Comment by DonBruce64** [comment]
After further consideration, I believe the current physics system works well enough to support a turboprop with either an aircraft or jet engine.  We can re-visit this when actual "turboprops" get in, but I suspect we won't have to.

**Comment by ff66theone** [comment]
I mean it would have been great to have turboprops for planes like the Vulcanair, with some additionnal prop options (because we literally have 4 props, helicopter included, no 4-bladed propeller at all)
Given the age of the technology, it could make sense as well for the Ford Trimotor since the first prototypes of the turboprop were made in the 1930s. Also I don't know why but the piston engine makes a sound akin to a turboprop's at low RPM, I don't know if it's me or if it's intended...
