### ISSUE TITLE
You should be able to damage a vehicle by damaging its parts.

### ISSUE THREAD

**Issue by Gliese-832-c** [DonBruce64/MinecraftTransportSimulator#1700]
I made a hot air balloon, where the basket is the actual vehicle and the balloon part is a separate part you attach.

I tried to see what happens if you shoot it down, but found out that apparently it does nothing. You have to hit the core part of a vehicle to shoot it down. This is unfortunately, because realistically, if you shoot the balloon part of a hot air balloon, it will go down. There should be some sort of setting that allows a part to transfer damage to the core part.

**Comment by boot2big** [comment]
Hi there! If you would like a part to forward its damage to the vehicle, simply define `forwardsDamage` in the `generic` section of the JSON as true.

It appears this wasn't listed on the wiki, I'll get on that to ensure no further confusion arises from this! (Because apparently we have `forwardsDamageMultiplier` on there, just not the actual forwarding parameter.)

**Comment by Gliese-832-c** [comment]
Ah, amazing to see that this is already a thing! Thank you for telling me about this. And yeah, probably best to edit the wiki to include that value.
