### ISSUE TITLE
New fuel type suggestion: Nothing

### ISSUE THREAD

**Issue by Gliese-832-c** [DonBruce64/MinecraftTransportSimulator#1701]
There should be a fuel/engine setting that uses no fuels, does not need to be started, has no gears, etc.

I want to use this for sailboats (for now I just set a custom fuel type that uses water so it's cheap), but ideally there should be some native representation for this.

**Comment by boot2big** [comment]
This can be somewhat accomplished using superchargerFuelConsumption (and superchargerFuelEfficiency), you'll still need a fuel type to be defined on the engine and the vehicle will need a defaultFuelQty. However you can make an engine that consumes approximately 0 millibuckets of fuel per tick.

**Comment by boot2big** [comment]
![image](https://github.com/DonBruce64/MinecraftTransportSimulator/assets/53581325/7e01db14-b416-4e9d-b8d5-b79cee7a5bf6)
Here's one example; you can set the SCFC to be equal to FC, ideally you won't want the SCE to be define at positive 1... otherwise you end up with an engine that doesn't have any power. You can do what I did by setting it to -1 (this actually gives it double its power) or just 0, which means it won't consume any extra fuel while still producing the same amount of power it normally should.

With that being said, I do not know if the latter will get legacy-compat'ed or not, but you'll know what you can do otherwise if that's the case.

**Comment by DonBruce64** [comment]
Eh, I can see this being a good thing to add anyways.  Something for stuff like bikes, sailboats, and horse-drawn carriadges N such.  Will add, IF the feller up thar tests in via Discord betas.  So @Gliese-832-c  ping me there when you're ready.

**Comment by Gliese-832-c** [comment]
Thanks for the reply. I'll hop onto Discord and ping you so we can discuss it further.

> 

What I did for now is make the main fuel consumption ridiculously tiny, and added a supercharged with a very high efficiency. However, I was not aware that you can use 0 or even negative numbers. Either way, it seems like DonBruce is willing to add a real nothing fuel type, but I appreciate the suggestion anyways.

**Comment by DonBruce64** [comment]
Addressed in 22.12.0.

**Comment by Gliese-832-c** [comment]
Thank you. Now I no longer need to pour water on my sail to make my ship go!
