### ISSUE TITLE
Player/entity can be damaged by other entities while sitting in the vehicle

### ISSUE THREAD

**Issue by Raptor324** [DonBruce64/MinecraftTransportSimulator#1752]
This can be good for civil cars, but when some mobs can damage you when you driving a TANK, that's bullshit. Plz provide the ability to make players invincible in certain vehicles, while such vehicle is not destroyed.

**Comment by boot2big** [comment]
This is actually possible given that the pack author puts some thought into it, although the system could perhaps have more modularity when it comes to this. However, all they have to do is apply a resistance effect to the player when they are seated in a vehicle!
https://github.com/DonBruce64/MinecraftTransportSimulator/wiki/Pack-Making-JSON-Potion-Effects

**Comment by Raptor324** [comment]
> This is actually possible given that the pack author puts some thought into it, although the system could perhaps have more modularity when it comes to this. However, all they have to do is apply a resistance effect to the player when they are seated in a vehicle!
> https://github.com/DonBruce64/MinecraftTransportSimulator/wiki/Pack-Making-JSON-Potion-Effects

Hmm, I got into the dude's pack and decided to try to add this function myself. I wrote the effects parameter to both transport and seat json, no errors. But the effect is not applied to the player. I don't know what to do.

**Comment by boot2big** [comment]
My own pack known as Immersive Vehicles Vanity features this for all cars, as I believe vehicles should be protective of their occupants. Check out my repository to see how it's implemented!

**Comment by DonBruce64** [comment]
Also, this is a pack issue.  Authors should be adding armor boxes in their tanks to stop bullets.  IV doesn't know the difference between a tank and a bulldozer, it's all how the vehicle is configured.

Also, the player could be outside the turret hatch, which is where they *should* take damage if hit.  Again, proper vehicle configuration will prevent this.  Labeling as invalid since it's not a code bug, it's packs not making tanks right.
