### ISSUE TITLE
[SUGGESTION] Pack encryption

### ISSUE THREAD

**Issue by andryqx** [DonBruce64/MinecraftTransportSimulator#1766]
Hello! I would like to share my idea, the essence of which is to encrypt the pack in some way. Unfortunately, in the MTS community there are many thieves of models, or the json code, who then pass off other people’s works as their own and post them on mod sites like curseforge. Is it possible to do something like this? at least for models. Like, is there any way for author to make their own code.. for unarchive jar file and change some assets?..

**Comment by DonBruce64** [comment]
There is not currently a way to encrypt the models in a pack.  Considering that all other pack-based mods like Immersive Railroading, Flansmod, McHeli, do not have the ability to encrypt models, I don't see a reason to have IV to start.  Now, I'm not strictly against the idea, but I'm not about to spend time coding it and learning all about encryption when there are other bugs in the mod that need killing off.  If someone wants to take a crack at coding it I will, but in the meantime model/JSON theft should be reported in the Discord, and I'll block packs sealing content from running.

**Comment by boot2big** [comment]
I will state for the record that, personally I'm actually a bit against the idea of encrypting _JSONs_ anyways since looking through a pack's code is precisely how new authors can pick up on ropes that the wiki can't teach them, as well as inspiration and compatibility for experienced PAs. I wouldn't care either way if models could be encrypted though, that seems fair 'nuff.
