### ISSUE TITLE
Request: Air Brakes and Reverse Thrust easy access

### ISSUE THREAD

**Issue by SYDoukou** [DonBruce64/MinecraftTransportSimulator#179]
A simple one, shouldn’t take too much time. 
We are lacking a very important control surfaces which is air brakes, Which makes us lost part of the control over speed mid air.
A simple air brake can be activated via B button in the air, and will activate ground brakes too when on the ground. It will have a smooth animation variable.
For reverse thrusts, going to the hud and then press the button isn’t so practical during fast landings. Maybe do it in a more realistic way so when engines are in idle and brakes are activated, keep pressing S will gradually activate the reverse thrust. The longer you press the stronger it is, just like normal thrust control. When releasing brakes it will automatically go back to idle.

**Comment by DonBruce64** [comment]
I'm not going to add a keybind for reverse thrust, as it's too easy to accidentally hit it during play and crash your plane.  The reason the button is in the HUD is to make it hard to press.  When landing you should be straight on the runway before you try putting on reverse thrust, otherwise you'll be crashing with the engines going backwards rather than forwards.  As to the control system of holding the throttle button down: the MTS control system isn't set up to handle held-down buttons differently based on the state of the vehicle.  You hit throttle down, it sends off a packet to the server to move that throttle down.  Nothing more, nothing less.

As to air brakes, I don't see any reason for them yet.  No users have complained about things being too fast, and with the new physics engine flaps are even more effective than they were previously.  Am going to close this ticket as a won'tdo, but may re-visit in the future should things change.
