### ISSUE TITLE
Clip through bigger vehicles say I am on a blimp or plane that is particularly large the player falls through the blocks

### ISSUE THREAD

**Issue by LittleTimmy52** [DonBruce64/MinecraftTransportSimulator#1813]
the title says it all execpt for its on 1.12.2

**Comment by DonBruce64** [comment]
Please show the vehicle in question, with the F3+B bounding boxes shown.  I've seen players fall through in 1.16.5, but not 1.12.2.  Perhaps the main bounding box isn't encompassing the other boxes enough?

**Comment by LittleTimmy52** [comment]
oh shoot, I forgot I made this issue, I am going to do that I was booting up the game anyways

**Comment by LittleTimmy52** [comment]
The berlin plane I showed worked mostly fine, but the generic one and the blip clearly had issues
https://streamable.com/ji3eue
it expires in 2 days, ill upload it again if i remember

**Comment by DonBruce64** [comment]
This looks like you have a mod or something conflicting with the player's collision and bypassing the normal code and enhancements that IV uses.  Try removing mods until you find the one that is causing this.  Alternately, you can join the Discord and we can chat there and go over things, but since I and others can stand on vehicles, this must be a confict with your specific modset.

**Comment by LittleTimmy52** [comment]
well unu vehicles work fine and collision with regular iv vehicles is fine just the big ones don't work fully and mainly near the driver/pilot seat

**Comment by DonBruce64** [comment]
Again, if you want this fixed, please follow my instructions.  You're the only one who has this issue, and unless we can find out why, it won't get fixed.

**Comment by DonBruce64** [comment]
Closing due to no response.
