### ISSUE TITLE
Design was terribal of the new Traffic (Mod: Immersive Vehicles - Official Content Pack)

### ISSUE THREAD

**Issue by Titoo8899** [DonBruce64/MinecraftTransportSimulator#1830]
hi,
the new Design of the new Traffic find I not so good. The Connect with the Pools was show bad and I find it to large. I hope you can change this and I hope you can the Connection to a pool better make.

![2024-07-31_18 00 44](https://github.com/user-attachments/assets/8b4744c4-fb8a-460d-ab14-a8dfbf26aa32)

P.S. This was your Idear of a Design but it is not so cool and the Functions of replace was not the best with the new Change

**Comment by DonBruce64** [comment]
@SnailPerson  This one is yours.

**Comment by Titoo8899** [comment]
The Design find you or a other person good but I think it is not so cool and have the dimensions overtop.

**Comment by SnailPerson** [comment]
@Titoo8899 for any future requests, responses and conversations, please use google translate. it isnt hard and it makes our life easier.
Just type "german englisch" in google, type the text in your native language and paste the result. thank you.

P.S. could your state our initial request for this post again. i o not understand what exactly you are trying to say here.

**Comment by Mike74846** [comment]
Hi,
I know that you can argue about design but I don't think the new traffic lights, pedestrian lights and lamps are that nice and they look too big. They are also not that easy to remove or place on the traffic light poles because the hitboxes are too hard to see, if they even have one. I have the same problem when I want to place the poles and increase them to 4 or 5 blocks because they don't show any hitboxes where I can connect them. I just hope that they rework it again so that they are just a little nicer or, as I would say, smoother. I also hope that there will be improvements to the placement and removal of the traffic lights, poles etc. in the next update.

**Comment by Titoo8899** [comment]
Hi,
I know design is debatable, but I don't think the new traffic lights, pedestrian lights and lamps are that nice and they look too big. They are also not that easy to remove or place on the traffic light poles because the hitboxes are too hard to see, if they even have one. I have the same problem when I want to place the poles and increase them to 4 or 5 blocks because they don't show hitboxes that I can connect them to. I just hope they rework this again so they are just a bit nicer or as I would say, smoother. Also I hope there are improvements in the placement and removal of the traffic lights, poles etc in the next update.

The rest of the update was really good, but it didn't meet my expectations, so I wrote this report to maybe get some small adjustments made.

**Comment by SnailPerson** [comment]
@Titoo8899 
-> you need to right click traffic lights etc. with a wrench to remove them.
-> The hitbox of poles does show for me when i aim the cursor on a pole. i see a little black box around them.
-> i scaled down crosswalk, traffic and blinking lights. they will be part of the next hotfix.

**Comment by DonBruce64** [comment]
Traffic light size was made smaller in OCP 26.2.  Calling this done.
