### ISSUE TITLE
Request: Prop feathering. 

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#193]
Going through my old requests, I found the one about a special propeller pitch rotation variable for controls in a plane. I mentioned that the zero point of that variable would be a feathered prop, not a minimum-pitch prop. Feathering a prop essentially means to rotate the blades so that the thin edge is pointed into the airstream. It reduces drag on the prop, increasing gliding distance for single-engine aircraft, and making a multi-engine aircraft easier to control in the case of an engine failure. This could be implemented by adding a "FEATHER" button next to the MAG/START buttons if they were assigned to an engine that produces force using a propeller _and_ if a variable-pitch prop was detected on that engine, so instead of MAG/START it would be MAG/START/FEATHER (or maybe some shortening of "FEATHER"). This would allow it to be activated individually, which is important as the main benefit of it is on multi-engine aircraft. It also has the nice bonus of making the existing prop pitch control rotation variable work, since feathering can be engaged by pulling the prop pitch control lever back behind minimum pitch. 

This Airbus A400M has a feathered prop on the engine that's on the right side of the image.
![image](https://user-images.githubusercontent.com/44233145/66316871-4714dc80-e8cd-11e9-8195-1b7107c8684f.png)

**Comment by DonBruce64** [comment]
Not sure I like having yet another button on the panel, especially when it's already this crowded with only three engines.  That, and I feel most people won't use such a feature.  Especially since the whole point of planes in the mod is to be run and realistic, but not to the point you have to worry about propeller feathering, fuel mixture ratios, and weight distribution of cargo.  Sorry, but I just don't see it ever being something I'll add.

![2019-10-07_21 31 04](https://user-images.githubusercontent.com/15241611/66363064-8fbeab00-e94a-11e9-9a73-22fe18cafac4.png)

**Comment by fsendventd** [comment]
Dang it... 
I wanted mixture controls as well...
