### ISSUE TITLE
Block Placement bug

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#211]
When any MTS block is placed (benches and decos), the block is always placed above the block that is looked at.

![2019-11-07_21 48 01](https://user-images.githubusercontent.com/36775575/68452888-ab66dc80-01a8-11ea-8701-0d6e034fc83f.png)
![2019-11-07_21 48 02](https://user-images.githubusercontent.com/36775575/68452889-ab66dc80-01a8-11ea-937f-4039776f989b.png)

**Comment by DonBruce64** [comment]
Yup, that's due to how I manually have to set the block rotation based on where the block is clicked.  MC doesn't have any built-in code for rotational placement that I can use (logs have other special logic that gets wonky) so I have to make my own.  Sucks, but that's MC for you.  I can tweak this to pick the block better, however.  I just always assumed people would click the ground to place benches and not a wall.

**Comment by DonBruce64** [comment]
Fixed in V15.6.0.
