### ISSUE TITLE
[Issue maybe] Container is saving air in NBT

### ISSUE THREAD

**Issue by slava110** [DonBruce64/MinecraftTransportSimulator#213]
Trailer container is saving all slots in NBT instead of saving only slots with items (like a normal entity/tileentity with storage)
![2019-11-09_16 28 32](https://user-images.githubusercontent.com/26705162/68529293-32819500-030e-11ea-804b-90bcf643511d.png)

**Comment by DonBruce64** [comment]
That's probably because I fill the slots with empty itemstacks, and save those when I save the inventory.  MC likely strips out the air in the save-load operations.  Will investigate to see how it handles such things in 1.12.2.  The save-load code got ported nearly direct from 1.10.2 when stacks were null rather than empty, so there's likely some inconsistency somewhere that's causing this behavior.

**Comment by DonBruce64** [comment]
Fixed in V15.6.0.
