### ISSUE TITLE
Flying Plane Upside-Down Results In Exorcist Shenanigans

### ISSUE THREAD

**Issue by Nianor** [DonBruce64/MinecraftTransportSimulator#22]
When you fly a plane upside-down, your head also inverts. It is quite disconcerting.
![2018-10-17_21 43 42](https://user-images.githubusercontent.com/11527859/47128266-297edb00-d256-11e8-9c55-9d3b61fa6940.png)
![2018-10-17_21 43 34](https://user-images.githubusercontent.com/11527859/47128267-297edb00-d256-11e8-8870-809847077042.png)

**Comment by fsendventd** [comment]
...that looks perfectly normal to me. If you're upside-down, your head should also be upside-down.

**Comment by Nianor** [comment]
It's more the "flipped 180 degrees and staring backwards" part that has me concerned. :P

**Comment by DonBruce64** [comment]
That's because the player's head points in the direction of the player's yaw, not the direction the camera is pointing.  When you do a 180 in a plane, you go past vertical pitch, which causes the yaw of the player to be inverted of where it normally would be.  When you add a clockwise angle to the camera you add a clockwise yaw of the head, which is actually counter-clockwise in that orientation.  I should be able to fix this with some trickery like I do the player body...

**Comment by DonBruce64** [comment]
Fixed in Commit c147e6aa9d6289ace53be089d28a085eeef000e5.
