### ISSUE TITLE
Water particules when vehicle hits water

### ISSUE THREAD

**Issue by TheOddlySeagull** [DonBruce64/MinecraftTransportSimulator#225]
It would be awesome, if a car or plane falls in water, to have a giant splash of particles (like the tank gif you sent)

**Comment by DonBruce64** [comment]
This wouldn't work well with a good number of packs, mainly due to the fact they don't have collision boxes except on the hood, trunk, and roof.  Would make for a rather funny particle effect.  While it does sound like a good idea, it's not really feasible given the collision box restrictions imposed by MC's block-based layout.
