### ISSUE TITLE
Corrupted my save ):

### ISSUE THREAD

**Issue by SpyTheMeme** [DonBruce64/MinecraftTransportSimulator#230]
[2019-12-14-4.log.gz](https://github.com/DonBruce64/MinecraftTransportSimulator/files/3970567/2019-12-14-4.log.gz)

**Comment by DonBruce64** [comment]
That log you just gave me is pure pain.  You have 277 mods, with over 60,000 lines of complaints and logging from Forge of mods doing things wrongly.  Plus another 10,000 of the mods logging things themselves, and another 200 or so of your server crying in pain because it can't keep up.  Even IF MTS's update broke your world, which I highly doubt given the fact I didn't see anything about MTS crashing, it wouldn't even help because you're out of RAM.

`[20:23:06] [Microphone/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.OutOfMemoryError: Java heap space`

Might be time to not install everything you see....
