### ISSUE TITLE
Signs rotated to face South upon new installation of Immersive Vehicles

### ISSUE THREAD

**Issue by TrafficAhead** [DonBruce64/MinecraftTransportSimulator#232]
I recently reopened my server after a while and took note that Immersive Vehicles updated.

Obviously, I updated it. However, the first thing I checked was to see that after installing, all of the world's signs were facing Southward. And the server has **tons** upon **tons** of signs that are now facing incorrectly.

Here is how they look:
![Annotation 2019-12-21 133447](https://user-images.githubusercontent.com/39660964/71312259-babb8580-23f6-11ea-9fb0-fa93034d479f.png)

This is not the first time it has happened but we thought the world had gone corrupt only with the signs.

**Comment by TrafficAhead** [comment]
![Annotation 2019-12-21 133722](https://user-images.githubusercontent.com/39660964/71312293-09691f80-23f7-11ea-98d7-7f4aa4f90b8f.png)

Here is an image to show that it doesn't work with just the custom signs we made.

**Comment by DonBruce64** [comment]
Unfortunately, this is a result of the block changes I made in the most recent version.  This is designed to reduce the code overhead and fix some performance issues with decor in large packs.  Essentially, the rotation of the signs are now stored in the blocks rather than the tile entities.  This is good, as it prevents de-sync issues with rotation and allows for quicker lookup for attachment of poles.  I'm afraid there's not much to do except replace them.  Expect this to not change in future versions, so this will be the only time you have to do such a thing.
