### ISSUE TITLE
[SUGGESTION] If possible, have the horn/siren scare/aggro mobs?

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#238]
I mean, honking a car horn at any animal would probably scare it.

**Comment by DonBruce64** [comment]
That's not possible.  Not because I'm not able to check for mobs, but because mobs do their scaring based on other mobs, not a bit or state set in their code.  e.g. Creepers only run if there's an ocelot nearby.  Unless I override a large portion of MC's code, I can't get mobs to run in fear of a semi truck, so you'll have to settle for just running down zombies like every other survival player.
