### ISSUE TITLE
Default values for variables

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#243]
If a customType (or other variable) is not specified, it is set to 0 or "", for example:

"customTypes" : ["", "bus"] would accept unspecified seats and bus seats.

This would also be useful for Ooferine's request on caster and offset for wheel steering angles because they could default to zero and not affect existing vehicles.

**Comment by DonBruce64** [comment]
But variables _do_ already initialize themselves to 0.  In fact, if a variable is left out it will initialize to 0, 0,0, or false depending on the variable.  So for Oof's request if nobody specified the origin it'd just get set to 0,0,0, or the center of the part.  That being said, strings/text just are blank, so that may be something I can adjust.  What's the point of having a part accept both regular seats and custom seats?  In that case why even have the custom seat?

**Comment by DonBruce64** [comment]
Implemented in V15.9.2.
