### ISSUE TITLE
Modded Blocks Replaced With Other Modded Blocks When I Load In {BUG}

### ISSUE THREAD

**Issue by RedneckGamer4020** [DonBruce64/MinecraftTransportSimulator#25]
[crash-2018-10-19_09.29.45-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/2496027/crash-2018-10-19_09.29.45-client.txt)
When I add MTS, UNU Parts Pack,  and Moonspire Metropolis Motor Pack to my current modpack I'm playing, and load into my world, I get a warning while loading (from Vanilla Fix mod) saying that my game is using a backup of the level data file, when I finally load in, random blocks are completely changed to other blocks, or just completely removed from buildings, as if the item id has changed, for example, bricks from chisel mod get changed to ME Controllers from AE2, or any other block in the game. And it eventually crashes. Is it possible to fix this issue? It also may be  important to note that this issue only happens to previously generated worlds, when I make a new world there are no issues.

**Comment by fsendventd** [comment]
....sounds like another mod's problem to me.

**Comment by DonBruce64** [comment]
This isn't another mod's problem, this is an issue with the level.dat file in your saved worlds.

All blocks in Minecraft have ID numbers to tell Minecraft what block is what in the level saves.  For Minecraft, all the IDs are the same no matter what (stone is 1, air is 0, etc.), but with Forge and mods, having static IDs would be horrid as every modder would have to reserve a section.  Instead, Forge assigns IDs from the next number available to the blocks, and stores what ID goes to what block in the level.dat file.  If you make a new world and add mods in a different order, the IDs will be different as different IDs were free when they were added.

If you're having issues with blocks being screwed up, it means that something in the level.dat file has changed to tell Forge that some IDs go to the wrong blocks.  Where once ID 2067 went to the Propeller Bench, now the file is saying that ID is 1457.  As you can imagine, this won't work as you'll load all the wrong blocks in the wrong places.  I actually had this once where ores turned to refrigerators due to me fouling up the level.dat file.

Either way, this isn't a MTS issue.  Either a mod seriously screwed up the level.dat file (and it's not MTS as it doesn't do world save/load operations), or you have a corrupted save file due to something not being moved correctly.
