### ISSUE TITLE
[Suggestion] Need better turning to compensate for lack of differential braking.

### ISSUE THREAD

**Issue by Colt44Magnum** [DonBruce64/MinecraftTransportSimulator#257]
Figured it would be best explained by this quick google searched video compared to just me horribly explaining it, but a tldr; tractors work differently than cars in the fact that you would set the gear you want to use before moving compared to a car that shifts gears while moving. The multi-range capability allowing for a high and low setting, would be nice but I don't think necessarily needed.
https://youtu.be/U3o9bsMRnyc
Another thing not mentioned in this video would be differential brakes which would be nice to have as well allowing for sharper turns in rear wheel tractors.
I found a playlist this video happens to be in if you want any other information, although not requested material at this moment
https://www.youtube.com/playlist?list=PLB4521CB0AC74171B

**Comment by DonBruce64** [comment]
So essentially this request is asking for two things:
1) Selectable gears for vehicles.
2) Differential breaking.

As to the first point, that already exists via manual transmissions.  Most pack authors don't include those as they cater to a more casual market, but they do exist.  Such transmissions do exactly what you ask: provide a selectable speed for idle movement.

As to differential breaking, this has been ask for a few times now, but doing such a physics update is difficult and would require two brake keys, something very non-intuitive for most users.  Because of this, I'll have to decline doing such a thing. Do tractors just not turn well enough for you?  Cause they should with their shorter wheelbases.

**Comment by Colt44Magnum** [comment]
Manual transmissions currently in do not work the same way that a tractors would at least in my playing with manual transmissions that the Trin Packs have added into the game. Or maybe I just misunderstand how manual transmissions for cars work currently. It might be due to them using gas pedals instead of throttles. Which I will be using on my tractors since that is realistic. 

As far as breaking goes when I drove the UNU Groundhog I didn't believe it turned sharp enough. While I understand that an updated physics system for just this would be too much to ask for really, I'd be happy if you just pondered on it. Maybe look into it whenever you work on other physics parts. In the case of keybinding there would technically need to be three keys or a switch in some way. I do agree that differential brakes are non-intuitive, I believe that 100% as I have seen people not realize that the two pedals next to each other are both brakes in real life. But as I said there would need to be three keys for braking with a differential braking system as most tractors and all modern tractors have a function to connect both brakes for use on the road, that is so you don't swing around throwing your tractor over while braking cause of someone in their car. I believe this can be done with the three keys we already have and have differentials be a toggle able thing that comes turned on by default under the U menu. Then for differential braking have it default to the keybinding such as s+d to use your right differential brake and make you turn right sharper, and s+a for left turning. Obviously keybinding is the easiest part in this case.

A final addition that I see I did not talk about is a PTO. I can't seem to find how ground effects are "started", from the video you posted it seemed as though they just need to be low enough to scrap the ground. Obviously rotatable objects are possible but I am curious as to how that would be made functional with the ground effects allowing us to "turn off" or lift up our equipment for transport. I currently dont have any examples to look at until Seagull finishes his industrial pack. I am sorry if this too is possible like you said the manual transmission can act in the same way as a tractors, I just cant seem to find it in the manual anywhere.

**Comment by DonBruce64** [comment]
As far as MTS engines are concerned, the gas pedal is just a throttle you actuate with your foot rather than your hand.  Every engine's current throttle position is internally managed via the localized control, so even though you have a gas key on cars and a throttle key on planes, it changes the same thing in the common engine code.  Call yours what you will and animate it how you like.  It'll work either way.

For manual transmissions, you essentially have multiple gears you can switch to via the shiftUp and shiftDn keys.  Using those you can select a vehicle speed as when idle you'll still have the engine running at ~500 RPM, which will give you a decent enough force from the engine to maintain your speed.  Granted, you aren't going to be able to maintain a speed of 30MPH this way due to the high drag, but most tractors don't even go that speed, and if they do they're likely floored anyways.

If it's turning radius you're looking for, that I can adjust.  I've had people make similar complaints about turning for planes, so it might be time to re-visit how I calculate turning code to see if there's anything I've missed that's making turning worse than it needs to be.  People have also asked for more responsive controls, so it might not be a bad idea for me to lump those two together into one change.  It's actually not hard for me to tweak the turning code as it's a separate section that's isolated from the main physics engine.  The worst part is the trigonometry that's usually involved in such changes.

As to the effects of the farming equipment, that's automatic.  Equipment that's ground-based (such as planters) will try to affect the block below them.  The fertilizer, however, tries to affect the block it's in, as it's assumed that the farming parts will be interchangeable on equipment and since crops are 1 block above the ground MTS needs to affect that block rather than the ground.  Moving parts are currently not supported, so the only way to turn off the equipment is to take it off the vehicle.  Moving parts are yet another thing that's been requested, but such code is very difficult so I've been slow to implement it.

**Comment by DonBruce64** [comment]
Turning should be better in V16.0.0.
