### ISSUE TITLE
[SUGGESTION] Quieter/Louder Engine Settings

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#258]
By default it's normal sounding, which is how it is now
Quieter engines are nearly silent when idling or below safe RPM, while louder engines... get louder at the safe RPM.

**Comment by DonBruce64** [comment]
But... why?

**Comment by boot2big** [comment]
Mostly because there's small and big engines, but now that I think about it, this might not be a super cool idea to be honest

**Comment by DonBruce64** [comment]
If it's based on engine size, then I could link it to fuel consumption.  The thing is, you generally can hear a lawnmower down the street just as well as a backhoe.  Really it's the type of engine more than the size that does it.  While I do agree that this would be a neat feature to have, I don't see many people using it , mainly due to MC's low render distance.  So I'm going to call it a "would like to do, but feel it won't be used enough to justify the effort" request.
