### ISSUE TITLE
Turn Signals are annoying

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#269]
The way they currently work now, you triple press A or D to signal, which results in signals coming on during microadjustments.
Maybe at least mod+turn to signal, a signal key (I know, another key, sorry) or having signals in the panels as arrows? (I'll try to make arrow buttons for this)

**Comment by DonBruce64** [comment]
The whole reason they're double-tap now is because they were previously a 2-key system that needed to go to free up the keyboard.  If you want to make the turn signal in the panel, that's fine, but I forsee problems with that.  Might just have them come on automatically when you try to turn the vehicle and go off when the vehicle is straightened out.  Would be simpler...

**Comment by InuYasha86000** [comment]
if someone is going to add buttons for signals I would say have a button for hazard lights instead first.

**Comment by DonBruce64** [comment]
Why not both?  I can make the button for hazards keep them always on, and if the hazards aren't on, then I'll just make them work as turn signals.

**Comment by StarterCraft** [comment]
Upvoting this problem too!

**Comment by DonBruce64** [comment]
Fixed in 15.10.0.
