### ISSUE TITLE
[Suggestion] Multiple Aircraft Cockpit's Instruments related Suggestions

### ISSUE THREAD

**Issue by StarterCraft** [DonBruce64/MinecraftTransportSimulator#283]
#### In this post I'd like to suggest some features related to the instruments inside the cockpit and ask some questions about the topic.

1. We need to have an abitity to make **realistic** electronic instruments **with HD textures** for our  cockpits. As I know, currently the instruments are not able to have specific design effects as on this Pic (look at the gauges):
![image](https://user-images.githubusercontent.com/43516901/73422400-d7d36480-4363-11ea-85fe-68d2ad20894b.png)

2. We need to make all-in-one instruments for our cockpits. It can be sth like modern airliners' navigation screens in the real life.

3. We need support for **yokes**, **sidesticks** and other things like them. 

4. We need to have a feature that makes us able to add separate throttles for each of the engines.

**Comment by DonBruce64** [comment]
Would prefer to have a separate ticket for each item, but since some of these items can be answered right now, I'll leave this ticket as a combination.
1) I don't see a picture attached, but you can make electronic instruments with bars.  Just nobody has done so, and when I've asked the people making jets for input on how to handle such instruments, I get conflicting answers.  Until the people who have a use for such things can agree on a standard, I won't be changing anything.
2) All-in one instruments are already possible.  The trim indicator indicates three things, while the electrical gauge indicates two.  Turn and slip also indicates two different properties.  If someone so wished, they could make a gauge with all 7, or even more.
3) Throttle yokes are already supported with the current joystick control system.  In fact, I've used a flight stick on MTS since it was MFS.  People also have used racing wheels, so I'm doubtful that such support doesn't exist in the Java system.
4) That would be rather hard to do, as most flight sticks and controllers don't have multiple levers for multiple throttles.  Code-wise it's not too bad, as I'd just put the throttle value in the engine rather than the plane, but it's another story as far as actually controlling the plane is concerned.  How would you choose to implement it?  Keep in mind most players use a keyboard.

**Comment by StarterCraft** [comment]
You didn't understand me correctly in the point 2. I was thinking about yokes and sidesticks in the cockpit of the aircraft, but I was not thinking about yokes for controlling the aircraft. 😊

**Comment by DonBruce64** [comment]
2) In that case, that is for pack authors to do, not me.  They can already do that with the current system, just most haven't gotten to that level of detail on their models.
4) How would players adjust the throttles, then?  The U-panel just has buttons, which aren't that condusive to quick adjustments.
5) Instruments already can be scaled to whatever size the pack author decides.  Again, it's up to the pack authors to implement that on their planes.

**Comment by StarterCraft** [comment]
Sure thing. I just wanted to make sure that the core mod supports instruments with HD textures and, I now guess, that's right.
As for #3 of your list, I am gonna make an separate ticket here for the U-Panel upgrade suggestion.

**Comment by DonBruce64** [comment]
Understood.  Will close out this ticket as everything else on it is already implemented in the core code and just needs pack author support.
