### ISSUE TITLE
[Suggestion] New U-Panel functionality 

### ISSUE THREAD

**Issue by StarterCraft** [DonBruce64/MinecraftTransportSimulator#284]
#### Currently the U-Panel has many problems: it is not very spacious, and it does not support any alternative textures, the trimmers're not very handy to use, and so on. Here's the list of U-Panel enhancements, which I would like to ask for:

1. U-Panel must have multiple tabs for separate purposes. Look how it is realized in Rortos's Flight Simulators: 
![image](https://user-images.githubusercontent.com/43516901/73406686-00426b00-4332-11ea-927d-bb4a414a291f.jpg)
I am going to suggest a quite similar concept. 
U-Panel has four tabs: engines' control, flaps', lights' and trim's tab, aircraft additional systems control and, maybe, navigation. The tabs will **not be opened with a separate keybinds for each one**. When the user is clicking his U-Panel button, he sees two halfcircles on left and right sides of his screen (the size must be configurable) (_if you do not understand, please look at my picture and see two halfs of circles on left and right side of the pic. Here's and additional pic:_)
![image](https://user-images.githubusercontent.com/43516901/73419770-58419780-435b-11ea-94bc-3494b3c584df.png)
 The circles have 2/3 letters like E and L and an arrow. On of the circles have an exit pictograph. When one of the circles open, the arrow is already set to the last position relatively what tab was opened last time. If the user clicks his U-Keybind again, the arrow rotates to the next position. If the current arrow's position was the last position of the circle, clicking the U-Keybind summons another circle and its arrow. If the U-Keybind has not been clicked for 3 seconds (this is also must be configurable), the selected tab of U-Panel opens and the circles disappear. If the selected item on one of the circles was the exit pictograph, then the circle just disappear and nothing additional will happen. Inside the U-Panel click on the U-Keybind will summon the circles again, and the user will be able to exit the panel or open another tab on the panel. _hope you understand_

2. The U-Panel now only supports two types of controllers inside of it, and only two textures of them are supported, with no ability to the pack makers to add custom textures to their aircraft' U-Panels. The U-Panel must support adding classic tumblers, rotating tumblers, throttles, various other buttons from the real planes in it. As I know, the problem is only that the custom textures for the U-Panel environment are not supported and new types of controllers are not added to the code.

I can continue the explanation, and I can suggest every single tab's structure. But first, I am going to wait for your response to this post.

**Comment by StarterCraft** [comment]
@DonBruce64, now waiting for your response. If my English is very bad and you can't understand what I am trying to explain, then say it to me, please.

**Comment by DonBruce64** [comment]
1) I will not be making a multi-tabbed U-panel.  The idea for that panel is to have a quick access to what you need in a vehicle, plus some gauges if you want to put them there.  I for sure don't need a whole three screens of giant levers and dials, especially since I can't get consensus on how said dials should be rendered for instruments.
2) I do plan on adding extra controls for things like tri-state switches for lights and possibly rotating dials, but that's dependent on how soon I get good textures.  As to the custom texture of the panel, that's already a thing, but again, pack creators tend to not care about that panel so it goes un-used.  Might behoove you to ask the pack creators if they even plan on using your feature suggestions prior to suggesting them, as it's they who drive what content MTS has, not I nor GitHub.

**Comment by StarterCraft** [comment]
I ask you gently to organize a vote of the mod users about adding this feature. Also, what's the issue of this suggestion? Why can't it be realized?

**Comment by StarterCraft** [comment]
This feature is necessary to add before adding much more other features, so I ask you to discuss this topic more before declining my idea.

**Comment by StarterCraft** [comment]
@DonBruce64, sorry for pinging so much, but I'll stop bothering You, if You'll give me clear reasons why you rejected my concept.

**Comment by DonBruce64** [comment]
I already gave you two reasons.  However, one MAJOR reason is this: How will I do what you suggested?  Excluding the code, where are the graphics for such a thing going to come from?  Not from me, as I can't do graphics to save my life.  So it's got to be someone else.  Even if I have the graphics, do you realize how much coding goes into GUIs?  Have you tried to code one?  Do you understand the hours that will need to go into such a request?  Making a new buttons takes a while, but is not horrid.  But making a multi-selector screen with multiple different buttons, textures, controls, and interfaces?  That's for a team of coders, not just me.  Just because you like a panel in one game does not mean I will re-create said panel because you ask.

**Comment by DonBruce64** [comment]
Ended up overhauling the panel in V17.0.0.  I'm calling this ticket closed, as the panel is now in a better state and where it should be.
