### ISSUE TITLE
[Suggestion] Autopilot

### ISSUE THREAD

**Issue by StarterCraft** [DonBruce64/MinecraftTransportSimulator#290]
#### Quite a long time ago, we've discussed a bit similar topic in #274. You've said that there're some navigation mods for MC already. Although, no one (_maybe I'm wrong_) navigation mod can't help very much in inflight situation.

So I suggest you to re-open the #274 discussion, because it's becoming actual right now. As what  should I say about autopilot, it is impossible to add without any navigation system. Anyway, the autopilot in IV needs to have 3 modes in it:

1. **Flight with the pre-selected parameters.** User sets up the necessary flight parameters, the aircraft's flying be them. This is simple.
2. **Flight using a automatic flight plan.** User places _flight navigation points_ along the route, any _flight navigation point_ has two parameters: X-Z coordinates and the altitude. Before the flight the user creates a flight plan with the points. After takeoff user activates the autopilot, and autopilot's flying the plane on the correct flight altitude following the points.
3. **Approaching mode.** User selects the runway area for the navigation system, and places the special _approach points_. If the user activates the autopilot with this mode, he must select the runway to approach and land. The plane follows the pre-installed approach points and lands automatically. `_This topic will be explained more in an another ticket._`

**Comment by fsendventd** [comment]
Not sure if you realize this... but MTS's code makes this a very difficult thing to achieve. Probably won't ever happen. Besides, flying is fun!

**Comment by DonBruce64** [comment]
No, no and no.  For one thing, very few people use planes for long-haul flights in MC due to poor render distance and performance.  Me coding a whole system of automated controls is not a good use of my time.  Such time would be better served doing other things, like fixing existing bugs, removing MC-specific code that keeps me from updating, or doing smaller tweaks that make the user experience cleaner rather than more immersive.  Not to mention it's another GUI change, of which I'm still trying to move away from MC's GUI system and am only halfway there.  Perhaps I'd consider something like a cruise control for cars and planes, but that's not nearly as helpful as one would think given all the twists and turns vehicles need to make.
