### ISSUE TITLE
[SUGGESTION] Have engines stall out when the RPM gets way below idling

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#321]
Sorry for making another issue/suggestion so quickly, but I was reminded of this while making the previous one.

Whenever an engine goes below idling and even reaches 0 rpm while running due to the car being pushed in reverse of the gearing, it just... keeps running.
eg. I put the car into Drive, but place a bucket of water in front of it (and we assume that the engine doesn't get water stopped) which pushes the car backwards and results in the engine slowing down... until it goes past said 0 rpm point and iirc, might've even gone below that.
The engine should be stalling or even stop running at this point, though maybe not with the actual stalling sounds.

**Comment by DonBruce64** [comment]
See now, engines used to do this, but I changed this behavior for playability reasons.  These reasons are as follows:

1. When using a plane equipped with a large propeller, you may end up accidentally killing the engine by moving the throttle so low that the engine can't keep up past the idle speed.  This is particularly a problem on vehicles with engines with higher hours, as they have lower compression and thus have less power and lower RPMs.  This caused lots of issues with the Bristol engines in the OCP as new players would start the engine, only to have it die right away as the idle throttle wasn't enough to keep it going.

2. When using a car, the speed of the engine is directly related to the speed of the wheels due to the drivetrain.  Because of this, when you shift into first gear you technically have a speed of 0 RPM on the engine for those first few ticks until you get moving.  MTS doesn't, and won't attempt to, emulate clutches, so the only way to handle this is to not stall the engine if it gets too low.  Sure your power can go to pot, but the engine won't die.

That being said, there is one case where this logic still applies.  That is when engines backfire.  If an engine backfires and drops the RPM below the stall RPM, *then* the engine will die out.  The idea behind this is that players will see the engine backfire and stall, so they can associate the two events and know to keep the engine running they need to keep it at a high RPM.  It's far more intuitive than the old system of the engine just "randomly" dying after starting or shifting into gear.
