### ISSUE TITLE
Stall Bug

### ISSUE THREAD

**Issue by Nianor** [DonBruce64/MinecraftTransportSimulator#33]
When planes fly straight up, what should be a conventional stall becomes a weird sort of slow motion impending doom. The planes don't nose down like most aircraft do in a stall, they tilt backwards and nose up, falling towards the ground incredibly slowly. However, despite their slow rate of descent, they will without fail explode on impact.

**Comment by DonBruce64** [comment]
Yeah, this bug has been around since the old MFS days of V08.  It's something that's wrong about the physics code that governs the plane movement.  I've looked at this before, but the trigonometry is tough and I couldn't immediately figure it out.  Since it's not game-breaking, I de-prioritized it.  Unless someone with more math skills than me gets a chance to look at it, you can expect this bug to linger.

**Comment by fsendventd** [comment]
~~did I tell you about the time I pointed a PZL straight up and got it to gain altitude?~~

**Comment by fsendventd** [comment]
~~heliplanes ftw~~

**Comment by DonBruce64** [comment]
Fixed (mostly) in V13.0.1.
