### ISSUE TITLE
[Suggestion] Plane Engine Flameout

### ISSUE THREAD

**Issue by SYDoukou** [DonBruce64/MinecraftTransportSimulator#334]
This is based on #320 , that engines won't just disappear when exploding.

If the exhaust POS is set for a plane, the smoke when it overheats will emerge from the exhaust rather than the engine itself. 

After the engine "explode" due to overheating or other reasons, the exhaust will spit flame particles and decrease it's thrust until it is set to idle or eventually reaches 0. When it is at idle rpm it will shut down and spit black smoke particles. 
It counts as broken engine, so it will not be crankable and drop it's crafting ingredients when broken, like what #320 suggests.

**Comment by DonBruce64** [comment]
"If the exhaust POS is set for a plane, the smoke when it overheats will emerge from the exhaust rather than the engine itself."

This doesn't make sense, as most overheating causes vaporization of fluids by the engine itself, not out the tailpipe.  Overheating is primarily a too hot-condition of the cylinders, engine block, etc, so it's not really applicable to the internal-combustion area.  Not to mention this code would apply to cars too, which is another problem as a steaming engine is usually the first sign that the engine is too hot, not a smoking tailpipe.

Now the fire outta the pipe?  That's possible for sure.

**Comment by SYDoukou** [comment]
Well in most cases whatever the plane engine emits comes out of the exhaust at high speed, I suggest that just because it would be weird to have smoke coming straight out of the engine housing while the fire comes from the exhaust.
Unlike cars, which don't have high exhaust speed and smoke coming out from the hood is an iconic indication that it's broken

**Comment by DonBruce64** [comment]
I'm going to roll whatever changes I do for engine death into #320.  As such, I'm marking this as a duplicate ticket and closing.
