### ISSUE TITLE
[Suggestion] Stall and other Alarms

### ISSUE THREAD

**Issue by StarterCraft** [DonBruce64/MinecraftTransportSimulator#345]
It'll be great to have audio and visual emergency alarms in our aircraft. The visual alarm lamps could be located on the U-Panel. Comment the thread, please, if there're any questions. :)

**Comment by fsendventd** [comment]
Actually, if you put a vertical speed indicator in your aircraft I believe it does make a noise when you enter a stall. I can't comment on others since you didn't give any other examples.

**Comment by StarterCraft** [comment]
> if you put a vertical speed indicator in your aircraft I believe it does make a noise when you enter a stall

This is wrong。 The device has no audible functionality.

> I can't comment on others since you didn't give any other examples.
**Additional examples:** any of them can be seen in [this](https://www.youtube.com/watch?v=8h5-wBnggMI) video.

**Comment by DonBruce64** [comment]
@fsendventd Actually, it was the Lift Reserve Indicator (LRI) that caused the audible alarm.  But that hasn't been a feature since we went to pack-based gauges.  The reason being you can't have a generic system with a single instrument that behaves differently.

@StarterCraft I disagree with having alarm lamps in the panel.  Nobody flies with the panel open as it inhibits the ability of the player to look around.  Putting the lamps in the panel would offer no benefit as the player wouldn't see them when they needed to.

**Comment by fsendventd** [comment]
@DonBruce64 Sorry, got the name wrong. And I didn't know that was removed, I thought the buzzer firing was just a feature of adding the lift reserve variable to a gauge.

**Comment by DonBruce64** [comment]
It was back before gauges were in packs, as each gauge was unique in the code and could be linked to other code bits.  But since all gauges are generic and defined via JSON bits, the system doesn't know what gauge does what.  Just that a gauge exists and how it should render it.

**Comment by StarterCraft** [comment]
@DonBruce64, you'd have an ability to install alarm lamps inside of the cockpit optionally.This's the best choice for visual alarms' invention.

**Comment by DonBruce64** [comment]
So, I'm going to call this ticket closed, if only because all the instruments that have the ability to indicate issues such as stall alarms and low airspeed may be rendered as a transparent overlay during flight.  This means there's no reason for players to *not* know that they're flying poorly as they'll have instruments for instant feedback, even in third-person.
