### ISSUE TITLE
Request: "Skid" hitboxes

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#35]
Would it be possible to add a boolean with the name "skid" to hitboxes? Because I don't want to make a part for my Camel's skid as it's barely 3 total voxels in volume, I would rather just add a small box to the main model and a small hitbox to the main model JSON that acted like a wheel/skid hitbox.

**Comment by DonBruce64** [comment]
This is actually something I've been thinking I'd need for some time now, as there are multiple instances of parts in vehicles that would be better off not being parts at all.  The PZL P11 skid is one such example.  This will likely have to wait for the hitbox update, though I may implement it sooner once I get out of the jet/helicopter territory.

**Comment by DonBruce64** [comment]
@fsendventd Can you show me where this skid is on your plane?  There may be an issue with this request.

**Comment by fsendventd** [comment]
A) sorry I didn't see this earlier, B) I never added it because I never got around to finishing the model (look up the real one if it's that important, C) it's in roughly the same sport as the P11's, maybe a bit farther forwards.

**Comment by DonBruce64** [comment]
So it's on the "tailwheel" area where the P11 is?  In that case, this hitbox cannot be just a skid as the skid itself must be used to turn the plane.  If I made it a hitbox, then you couldn't turn the plane except using the front wheels, which would make it very wrong.

Now as to why I can't just make it a skid: because MTS is expecting a part that has width and friction and tractive forces.  Hitboxes don't fall into this category at all, so I won't be able to get them to work nicely with wheel systems that you'll be needing for this particular case.

**Comment by fsendventd** [comment]
Hmmmmm.

**Comment by DonBruce64** [comment]
This cannot be done without SIGNIFICANT changes to how MTS handles collision and steering.  No support.
