### ISSUE TITLE
Mod config file?

### ISSUE THREAD

**Issue by Onikage056** [DonBruce64/MinecraftTransportSimulator#373]
So, this is a thing... there's no accessible config file for the mod. At all.
I checked the config directory after noticing it wasn't accessible in-game.
In a parody of Portal: The config file is a lie.

Edit: nvm... found it.

**Comment by DonBruce64** [comment]
Out of curiosity, why didn't you see it at first?

**Comment by Onikage056** [comment]
I was looking in the config folder for a standard config file, y'know, the text document type. Didn't stop to think it could be a JSON file. Incidentally, JSON configs can't be changed in-game.

**Comment by fsendventd** [comment]
> 
> 
>  Incidentally, JSON configs can't be changed in-game.
@Onikage056 While this is true for the vanilla config system, MTS has a config section accessible by pressing P and clicking config when the GUI comes up. It doesn't let you change everything, but the things omitted don't take effect until a restart anyway so they'd be useless.

**Comment by DonBruce64** [comment]
Judging by the wording, I think the user is implying that JSON configs can't be changed in-game, but Vanilla ones *can*.  If that's the case, I can see about including a button on the config screen to re-load the JSON config.  That's an easy command to do on singleplayer systems.

That being said, I'd rather put the configs in the GUI to be edited rather than the JSON.
