### ISSUE TITLE
A few issues/ bugs that I've noticed while testing out the new version

### ISSUE THREAD

**Issue by SanjivanM** [DonBruce64/MinecraftTransportSimulator#406]
I used to play on one of the older versions, so I loaded in the new version in a testing environment to give it a spin (literally), and I've noticed several things:

- MTS Military Defender has only 1 main instrument slot, as opposed to 4 in the older versions, The Seagull Milit. pack hasn't been updated in a while, so it seems to be a GUI handler thing with the main MTS mod?
- Trin gauges don't seem to be updating, but the Official Pack ones do.
- Scout moved by itself, even when off.  Seemed to have momentum/ no friction.  The vehicle had all wheels, etc.  Bounced off blocks (blockBreakage=false)
- Activating Parking Brake on some vehicles (Seagull Defender) moves the vehicle door veeerrry slightly, but does not fully open.
- Shifting gears doesn't seem to move the gear shift or shift gears, I verified that the engine was running, and retried.  Still nothing

Sorry if this is a lot, as you can tell, haven't updated MTS in a WHILE :P
MTS mods used:
- Seagulls military pack 1.7.4
- Immersive Vehicles 18.1.4
- IV Trin Part Pack 2.8.1
- MTS Official Pack V16

Other mods in test environment
- IC2, using biogas as the fuel
- MCA, to see if MCA villagers could be moved (see Issue #405 )

**Comment by fsendventd** [comment]
Trin hasn't been updated in a long time. It's not up to date with the new MTS rotation conventions or instrument positions, so that's why the instruments are weird and the doors don't open. As to gear shifting, not sure about that. That's odd. 

And about MCA villagers, they can't be moved because they're not a Minecraft villager entity. The ticket only works on vanilla villagers because it detects that specific entity type. But if you can put a lead on them (which hopefully you can't but if you can then whatever because it's Minecraft), you can do that and right click (maybe sneak-right click?) a seat to put them in it.

**Comment by SanjivanM** [comment]
Yeah, you can't put a lead on the MCA villagers, but I was thinking, could MTS also detect instances of EntityVillagerMCA, then handle that? Because that's what MCA replaces them with.  As for sneak+clicking, that's on MCA's end to patch, and I've sent a PM on Curse to the author about that, hopefully, if they don't patch it themselves, I could manually patch and make a PR. 

Any chance that the Trin packs will be updated? I didn't see the source on GitHub, and I'd really like to use those vehicles in my base.

**Comment by fsendventd** [comment]
Theoretically it's possible, but technically MCA is at fault for replacing villagers so it's not likely to be done by Don. I can take a look soon.

As to Trin... the author of those packs, TheOddlySeagull on Discord, has been kinda stuck. Life happened, and with the human malware issue right now... well, updates are really slow. 

~~if you want some pretty planes I'm going to be releasing some in the DWT pack pretty soon~~

**Comment by SanjivanM** [comment]
True, but that's kinda the point of MCA :P Possibly detecting if MCA is installed, like I mentioned earlier, would enable MTS to not look for instanceof EntityVillager, but rather instanceof EntityVillagerMCA, if that's how the code does it (haven't taken a look at that part).

And yeah, life happens, so I'll probably stick with an older MTS version until I find a suitable replacement (UNU seems like a good one), but yeah, life :P.

**Comment by SanjivanM** [comment]
As for the scout sliding around...  PARKING. BRAKES.  Guess I bugged out instead on this one.

**Comment by DonBruce64** [comment]
Checked on the MCA codebase.  They do in fact extend EntityVillager, at least from what I can tell, so for all purposes they *should* behave just like the regular villagers.  As to the gearshift, that's also a rotation thing that the Trin packs aren't current on. Nothing to do about that but wait.

**Comment by SanjivanM** [comment]
MCA Villagers do not seem to respond to tickets.  Possible fix could be overriding their GUI from being opened when holding a ticket, but I'm not sure if this is feasible.  Alternate fix would be MCA's author patching Sneak clicking.

**Comment by DonBruce64** [comment]
Ah, but do they mount if you are in a vehicle and then use the ticket without clicking anything?  (Clicking the air, not a vehicle collision box)

**Comment by SanjivanM** [comment]
Oh! Yeah, they do!  That is *very* interesting... They also disembark when the ticket is used, however, the ticket seems to pick up the closest MCA villager, which can easily be solved by getting the preferred villager to follow you to another place...

Also, when villagers (specifically MCA, because that's what I use) disembark, they're placed next to the vehicle, but players get dropped seemingly 1 block above the seat on which they were on, which tends to glitch you into the roof of the vehicle.  You take no damage, but it takes a few seconds to get out of the glitchy zone.  Tested on the scout.

**Comment by DonBruce64** [comment]
That makes perfect sense, then.  Rather than letting the item work on the villagers, the GUI opens, preventing them from being ticketed.  As to the embarking, it's just a 15-block radius where all villagers get picked up.  Didn't want to go much further than that given I've got other things to work on.

Disembarking is done based on the dismount position of the vehicle.  Be you a player or a villager, you should be disembarked in the same location.  That being said, if that location is blocked, or the creator of the vehicle didn't define a disembarking location, you'll get just dropped right out of the seat and MC does a "best guess" check on where to put you.  It's frequently wrong, as you no doubt have seen.

Finally, as to buses, UNU has a few, but some of them dismount you in the floor.  The double-decker bus in particular does that, which shoves you into the ground.  Not fun.

**Comment by SanjivanM** [comment]
Cool! Thanks for the help! The disembarking is fine, as long as I don't get damaged.  I have commands on, so I can just /tp myself out of a glitchy situation.

**Comment by DonBruce64** [comment]
You're welcome!  I'm taking a bit of a break from coding right now, so this ticket about tickets will likely linger for a while.

**Comment by fsendventd** [comment]
so don

when are you coming back

me and emerald need you for help with some complicated rotatable model objects

**Comment by DonBruce64** [comment]
Not until I feel ready and I won't burn myself out or get frustrated.  And being asked to come back to do math don't sound like it'd help either of those two things.  Playing Stardew Valley is far more fun than coding right now, so that's what I'm gonna do.

**Comment by SanjivanM** [comment]
So I guess now's not the time to make a suggestion about auto-speeding ticket giving thingies?

**Comment by DonBruce64** [comment]
So after reviewing everything on this ticket, I've noticed that it's all due to other packs not being correct, or GUIs that I can't override, but that thankfully there are other designed work-arounds for.  As such, I'm closing this ticket.
