### ISSUE TITLE
[Suggestion] Automatic Speeding Ticket Issuing (and related content)

### ISSUE THREAD

**Issue by SanjivanM** [DonBruce64/MinecraftTransportSimulator#409]
I think some sort of sensor system could be implemented, where server OP's can set a certain speed (and direction) that vehicles must be going, e.g. North, max speed of 10 Blocks/Second, and when vehicles are going too fast or in the wrong direction, a stat can be added to the Player (numTickets+1), and if they have a certain # of tickets that they have not paid (more on that later), they will not be able to get in the driver's seat of a vehicle, and get the message "You have too many unpaid tickets (numMaxTickets).  Please visit [serverOP] to have them paid."

The sensor system would probably need 2 blocks, places in a straight line, defining the line of "sight", like this:
![image](https://user-images.githubusercontent.com/33943333/80845515-4c65ab80-8bbe-11ea-9435-8298ea389e0b.png)
When a vehicle crosses the sensor line, and is going too fast, it would log that in the console, add to the driver's variable (getting player from vehicle, maybe?) and notify the server OP (or host of LAN worlds).  Let's call the driver Player1, and the server admin, well... admin1.

Then, admin1  would then be able to collect the fine(s) from Player1, then using an admin-only tool (available only via commands, perhaps), decrease the Player1's numTickets by whatever number admin1 desires.

The sensors could only be "programmed" by admin1, and he could set the speed and direction at which the sensors would trigger.  A blacklist could also be implemented for players on the server either working for the police, or for the admin himself.  Vehicle-specific tags are another way I think this could be implemented, assuming each vehicle uses it's own UUID?

Additionally, admin1 could use his ticket managing tool to manually ticket others, either by vehicle, or by entering a player name.

**Comment by fsendventd** [comment]
This sounds... really complicated. And probably really annoying for a lot of people. Imagine not being able to get in your car just because you have unpaid speeding tickets. At that point you might as well implement drivers' tests and licenses. And AI police.

**Comment by DonBruce64** [comment]
I could care less about annoying people with tickets.  The whole point of such a system is to reward people who follow your server rules (or those who are smart and know where all your speed traps are).  What's hard is coding such a system.  Especially because I'd have to mess with global world data to keep track of ticket fines.  Been years since I've done that.  You're also asking me to look into game commands.  That's an area I've never touched.  Basically, what you're asking is for a whole bolt-on system to be designed when I can't even get basic things like auto-unloaders and vehicle riders to work properly.  Not gonna duh right now.  Ask again in 6 months or when another coder joins the project, whichever comes first.

**Comment by SanjivanM** [comment]
Yeah, makes sense.  Sorry if it seemed too overwhelming.  It looked better in my head...

**Comment by DonBruce64** [comment]
I mean, I'd love to do it.  In fact, I've always wanted a system where you could make police chase after players for running red lights, but doing that is quite hard and would take time off of other things.  This is one of those areas where teams like Immersive Engineering get good because they can divide and conquer.

**Comment by SanjivanM** [comment]
Well, there *are* speedometer-ish mods (https://www.curseforge.com/minecraft/mc-mods/squeedometer), however, at this point it's just a honor system.  This feature could just be on the "wait for more people list"
