### ISSUE TITLE
Setting for left or right side of the road

### ISSUE THREAD

**Issue by Aunuli** [DonBruce64/MinecraftTransportSimulator#42]
I have had this idea for a little while and think it would be a good thing to implement. I think the config needs a new variable for the side of the road the cars are intended to drive on. Most MTS models at the current moment are designed for right side of the road but that really limits creative freedom with road layouts. So how this would work is that each vehicle's JSON has a value for the side of the road it was designed for. Then inside the mod config you could specify what side of the road cars drive on and the vehicles that their JSONs don't align with that would have their models flipped across the length of the vehicle to make things fit better. This would come in very handy in cases such as buses, garbage trucks, mail vans, and any other vehicle intended to have something facing out on one side relative to the road's center.

**Comment by DonBruce64** [comment]
How would this affect such things as lights?  Also, if I mirror the model, all animations will be mirrored as well, which would result in a model that turns right but goes left.  I'm not opposed to such a feature, however I'm not sure if the implementation can be done easily...

**Comment by Aunuli** [comment]
Yea, the more I think about it the worse the idea I had for implementing it is but I still think it would be a great touch.

**Comment by DonBruce64** [comment]
So I actually decided to try and implement this today.  The flipping of the model itself was trivial, and I had no issues there.  The part rotation was fine too, as I didn't flip those and since vehicle wheels are symmetrical MTS didn't care about them being on the opposite side.  What eventually stopped me was the seats.  When I flip the model, the driver seat is still defined as being on the left side.  I can move it to the right side by inverting everything, but then that still leaves the matter of the steering wheel.  The animation for that will be inverted if the model is flipped, and if it's a part it will be on the wrong side too.

No, I think the simplest solution is to just design the model from the get-go to be sided.  I know it's more work from a modeling standpoint, but from a pack standpoint it's just a slight tweak and copying the JSON files.  The code that needs to go into MTS to implement this would not be clean, nor would it be fast.
