### ISSUE TITLE
[Suggestion] JEI support for MTS crafting systems?

### ISSUE THREAD

**Issue by SanjivanM** [DonBruce64/MinecraftTransportSimulator#450]
It gets *really* annoying to click through the GUI's to find one part, and sometimes you skip over it, or just don't know the crafting block to use (component bench or decoration bench) and would be much easier to have JEI tell you the crafting block needed, as well as the required materials, for those who get ALL materials beforehand

**Comment by DonBruce64** [comment]
I fail to see why you need to click through all the GUIs when there's a search function built into the default creative tab system.  Not sure how JEI would help you find all V8 engines any better than this.

**Comment by SanjivanM** [comment]
I was talking about crafting in survival mod, should've mentioned that...

**Comment by DonBruce64** [comment]
Ah, that's different then.  Do you happen to have any documentation of how to interface with JEI?

**Comment by SanjivanM** [comment]
Unfortunately, no, but there are several mods that add in their own crafting systems that also add JEI recipes (IE, ExtraUtils2, to name a few)

**Comment by DonBruce64** [comment]
Figuring out how a mod works by looking at other mod's code is not as simple as you may think.  That's like trying to figure out how to make a GPU work in a Windows machine by looking at a Macbook.  Totally different architecture, and there's no rules or starting position to go from.  Going to table this until some documentation is found, or until someone chimes in with a how-to.

**Comment by DonBruce64** [comment]
So, I tried following the tutorial, but couldn't even get past the Gradle system due to something being wonky with the libraries Gradle was trying to pull in.  It seems it could pull in the api library, but couldn't pull in the compile-time jar.  Leaving this for future reference if someone else takes a second look.  I'm going back to tabling this for now.
![image](https://user-images.githubusercontent.com/15241611/100536699-eee31d00-31e7-11eb-9b50-017baa4351f9.png)

**Comment by DonBruce64** [comment]
So, I tried following the tutorial, but couldn't even get past the Gradle system due to something being wonky with the libraries Gradle was trying to pull in. It seems it could pull in the api library, but couldn't pull in the compile-time jar. Leaving this for future reference if someone else takes a second look. I'm going back to tabling this for now.
![image](https://user-images.githubusercontent.com/15241611/100536719-0d491880-31e8-11eb-8532-6ee41292432f.png)

**Comment by DonBruce64** [comment]
Did more tests today.  Ended up having users get locked-out on their end because JEI was being flagged as a required dependency.  If anyone can get around this, I'm all ears.

**Comment by NightScale5755** [comment]
Alright. So...
An extensive google search led to the following 2 links:
http://cazzar.net/tutorials/fml/optional-annotations-the-usages/
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/mapping-and-modding-tutorials/1571434-tutorial-modding-with-apis

Hope this helps!

**Comment by DonBruce64** [comment]
Implemented in V20.0.0.
