### ISSUE TITLE
Joystick config does't clear when unplugged

### ISSUE THREAD

**Issue by FightingPickles** [DonBruce64/MinecraftTransportSimulator#454]
Joysticks can active in the config even when not plugged into the computer. Turning off keyboard override does not fix. Can provide config.json if needed

**Comment by boot2big** [comment]
Vouch. I don't remember which log was made when I had my controller out (lost it a little bit ago) but this does indeed happen. I have to go and manually clear it in the config if I don't plug in the controller :(

**Comment by DonBruce64** [comment]
Fixed in V18.3.0 by making the ControlSystem not query joysticks that weren't present when MC was launched.  Do note that if you launch MC, bind the joystick, and then un-plug it, MTS will still query the un-plugged joystick for input as it doesn't know that it's been un-plugged as Java doesn't report this information.
