### ISSUE TITLE
Fuel gauge stops working

### ISSUE THREAD

**Issue by DarkNH3** [DonBruce64/MinecraftTransportSimulator#458]
When going far away from the vehicle or restarting the server, and coming back to the vehicle and starting it, the fuel gauge displays a fuel amount until starting the vehicle. After starting the vehicle, the gauge drops to Empty, but the vehicle continues to run. This makes it hard to know when to refuel. 
This happens with gauges from various packs. Using version 18.2.0.

**Comment by DonBruce64** [comment]
This sounds like the vehicles are forgetting what type of fuel they have inside them, and then the vehicle resets its fuel.  If this happens, and you log off and log on, do the gauges show the correct amount?  Because if there's really 0 fuel in the vehicles, then they shouldn't run.  But it sounds like your client isn't getting the fuel correct and makes the vehicle have 0 fuel, but the server says its okay.

Can you post your server mtsconfig.json, as well as your client mtsconfig.json on your computer?

**Comment by DarkNH3** [comment]
Relogging caused the fuel to display incorrectly, but the vehicles continued to function as if they had fuel on the server side. 

Regardless, I copied the server mtsconfig.json to my client config, and that seems to have resolved it. I didn't realize that having the same config was necessary to display fuel accurately.

**Comment by DonBruce64** [comment]
The same config is required as a lot of the code that runs on the server also runs on the client.  When you configs don't match, the server says that the vehicle is using one type of fuel, but the client says it can't use that fuel, so the client sets the fuel to 0.  But even though the client wants to turn the engine off, the server prevents this as the engine is still on, so that's why the vehicle continues to run.
