### ISSUE TITLE
[BUG?] Weird tranny behavior when a second reverse gear is introduced into the equation.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#467]
Expected behavior, you have a second reverse gear to shift into to go faster... for some reason. (iirc this may or may not be used for heavy trucks, but i might be wrong)

actual behavior tl;dr reverse is second rev gear, neutral is reverse, first is neutral, second is drive

Actual behavior, your first reverse gear becomes... neutral? When the engine is in neutral, it's actually in reverse. If you put it into reverse, that's the second reverse gear. Put it into drive, and you're now in neutral, and the gearing is set to 0, making it really hard to move! You can try and floor it and _maybe_ MTS will go into a higher gear, but it's hard to get moving.

Probably not an easy fix, I don't blame you if you don't want to work with this ticket.

**Comment by DonBruce64** [comment]
Actually, I can do this ticket, but it'll require someone to make an engine with multiple reverse gears.  Right now I assume in the code that there's only one negative gear behind the 0 neutral gear, but since neutral is actually defined in the JSON, it's possible to determine how many reverse gears a transmission has dynamically.  Reckon I was a bit more forward-thinking when I defined this standard than usual!

Again, engine/pack before feature.  Though that's not a guarantee if I find myself waiting for vector help for this update and start hitting other feature tickets.

**Comment by DonBruce64** [comment]
Implemented in V18.3.0.
