### ISSUE TITLE
[Enhancement] Different Engine Temperature with Serene Seasons support

### ISSUE THREAD

**Issue by FranklinMCA** [DonBruce64/MinecraftTransportSimulator#472]
In different seasons the basic engine temperature growing or decreasing. So it will be cool to add Serene Seasons support.

**Comment by DonBruce64** [comment]
Engines already support temperature changes for biome temperature.  This comes from the world itself, so serene seasons should be able to override the function that reports temperature and return a correct value.  If not, I'm not about to add-in another mod to my existing codebase.  I already have OpenComputers support, and the only I reason I have this is because someone else coded it.  So the same rule applies here: you want it, you code it.
