### ISSUE TITLE
[Suggestion] Flansmod + MTS Damage System Compat

### ISSUE THREAD

**Issue by ytHighQ** [DonBruce64/MinecraftTransportSimulator#477]
Maybe it would be possible to add some form of compatibility between flans mod and MTS by allowing flans mod vehicles to damage MTS vehicles (and MTS vehicles to damage flansmod etc,.) due to there not being that many MTS militarized vehicles out ATM as it is a fairly new and unknown mod. I personally feel that doing so would allow for better flexibility when it comes to modpacks that have both mods installed. Keep up the good work btw!

**Comment by DonBruce64** [comment]
This is a good idea, but will take time as MTS doesn't have a damage system like Flansmod.  Given that there aren't many tanks or guns in MTS, I'm going to table this for now, but I do want to look into it in the future.

**Comment by DonBruce64** [comment]
So, I was able to fix compatibility with Vic's Modern Warfare in V19.6.0. However, all testing showed that when a Flansmod bullet hits an entity, it does not call that entity's attack code.  Since Flansmod isn't calling the attack code, there's no way for my vehicles to know they've been attacked, and therefore no way to do any compatibility.  That being said, the reverse needs to be true on Flan's end: I call the entity attack function, so if they are ignoring that, then that's on them.  In essence, there's nothing I can do for Flansmod compatibility, so that's wholly on their end to fix.
