### ISSUE TITLE
(Enhancement) Rendering text on custom parts

### ISSUE THREAD

**Issue by Lemmy-Disturbed** [DonBruce64/MinecraftTransportSimulator#483]
I want to see this because of a few parts I will end up making for DAM Aftermarket Division Pack (This would be a community parts pack for my vehicles and those that use the same mounting locations on their vehicles) such as bumpers, grilles and other stuff but it would be separate from the normal vehicle text on any given vehicle... This would allow for one to use a template and not have to worry about modelling letters on a part

**Comment by DonBruce64** [comment]
Possible, but I'm going to defer this until I get the rendering update in.  In that update, I'll be messing up how text is rendered anyways, so it'll be a good place to add this.

**Comment by boot2big** [comment]
Would it maybe be possible for custom part text to be separate from vehicle and other part texts?

This would allow for a car to have a custom liveries with text like "(server) police dept" or "CRAFTED SPEEDSTERS" while also having a license plate, and additionally having vehicle text, if pack devs want to have plates on the car at all times rather than being able to take them off.

It could be controlled with an anvil for renaming.

**Comment by DonBruce64** [comment]
That's the general idea.  You have a list of text boxes that are on the vehicle you can edit, and those boxes come from the vehicle itself or parts on the vehicle.

**Comment by Lemmy-Disturbed** [comment]
I just realized that scaling might be an issue once one passes a certain amount of characters like 5 to 7 or even 9 characters depending on what part it is or if there is a potential chance that a limit can be set to prevent weird issues with rendering that part if the text goes outside of specific bounds

**Comment by DonBruce64** [comment]
Added in V19.0.0.
