### ISSUE TITLE
Suggestion: Have more than 6 radio station folders?

### ISSUE THREAD

**Issue by SanjivanM** [DonBruce64/MinecraftTransportSimulator#495]
That would help (maybe) categorize your music
Selecting the station would probably have to be a built in window to select the folder (from mts_music), which might be a bit complex to code
Also, the ability to select which song from a folder to play would be cool...

And here's my take on this, feel free to deviate.  This assumes you've selected "PC"
![2020-07-18_18 06 55](https://user-images.githubusercontent.com/33943333/87864860-7b203200-c922-11ea-93d2-3641690b9c25.png)

**Comment by DonBruce64** [comment]
What you have there, and what it appears you're going for, is an entire media player setup for playing music.  If you want that, then you should just use your computer's built-in player.  The point of the vehicle player is to not be that, and be more reflective of an actual radio.  Most radios only have 6 presets, and as such there are 6 buttons for folders.  I really don't see why you'd need more than 6 different playlists.  Especially since you can choose the order the music plays in within those lists.
