### ISSUE TITLE
Request: Stackable caution cones

### ISSUE THREAD

**Issue by obsidian29** [DonBruce64/MinecraftTransportSimulator#5]
I would love to be able to stack caution cones in the corner of a workshop, and to mount them on construction vehicles. Aesthetic, though they'd fit better in crates.

**Comment by DonBruce64** [comment]
Stackable cone blocks, while technically possible, are better left to a separate model for performance reasons.  I don't want to hard-code decor blocks to do special things, as it makes the code far less flexible and easier to update.  The model will have to come from either the main system, or a decor system as referenced in issue #4 .

Stackable cones on vehicles, however, are up to pack creators to make, not me.  The JSON block model and the OBJ vehicle models are incompatible with one another, therefore cones cannot be "placed" on vehicles per-se.

**Comment by alexiokay** [comment]
## Entity Disappearance Race Condition Fix Applied

**Fixed in commit:** [774451eb7](https://github.com/alexiokay/MinecraftTransportSimulator-NeoForge/commit/774451eb7) - *Fix entity disappearance race condition during world loading*

### What was implemented:
- **60-tick (3 second) retry mechanism** for missing entity factories during world loading
- **Intelligent retry logic** instead of immediate entity abandonment 
- **ENTITY RECOVERY logging** for debugging and monitoring
- **Graceful cleanup** only after maximum retry attempts exceeded

### How to monitor the fix:
If entity disappearance occurs again, look for these log messages:
- `ENTITY RECOVERY: Entity factory not found for ID: 'X' (attempt Y/60)`
- `ENTITY RECOVERY: SUCCESS - Entity 'X' loaded successfully after Y attempts`
- `ENTITY RECOVERY: FAILED - Entity factory never found for ID: 'X' after 60 attempts`

### Next steps:
1. **Test and observe** - Monitor for entity disappearance in normal gameplay
2. **Check logs** - If entities still disappear, search for ENTITY RECOVERY messages
3. **Report findings** - Add log files or specific log entries to this issue if problem persists
4. **Fallback plan** - If no improvement observed, we'll revert this commit and investigate **Cause #2: Client-Server Position Desync** (updateInterval timing issue)

The retry mechanism addresses race conditions during startup when entity factories aren't fully registered yet. If entities still disappear, it indicates a different root cause that requires further analysis.

**Comment by DonBruce64** [comment]
@alexiokay Wrong repository.
