### ISSUE TITLE
Use OreDic for Dyes in Recipes

### ISSUE THREAD

**Issue by kandivia** [DonBruce64/MinecraftTransportSimulator#62]
Some recipes, involving most the dye recipes, don't use the Ore Dictionary, they should. Fuel pump for example.

**Comment by kandivia** [comment]
Bonus Points if Ore Dictionary is supported for the various crafting stations

**Comment by DonBruce64** [comment]
Isn't OreDict going away in 1.13?  I hesitate to support a depreciated feature knowing full well that once 1.13 drops most people will jump to that and I'll be dealing with something that's a pain to yank out as I can't port over.

**Comment by kandivia** [comment]
True, 1.13 will introduce tags which seems to be replacing oreDic

**Comment by DonBruce64** [comment]
@DrprofLuigi can you elaborate on that?  I don't quite follow.

**Comment by DonBruce64** [comment]
Closing issue due to lack of response, and the fact that OreDict is going away in 1.13.  When it comes to crafting with custom items, you are always welcome to modify the Packloader java file to use different crafting bits with benches based on what mods are loaded.  Either way, I'm not doing it internally due to the constant changes to crafting that Mojang/Forge keep implementing.

**Comment by DonBruce64** [comment]
Re-opening, as I'm actually going to be sticking to 1.12.2 and this is a feature I can, and will, support now.

**Comment by DonBruce64** [comment]
Implemented in V19.13.0.  OCP will use OreDict in its next update.
