### ISSUE TITLE
[Suggestion] Option for vehicles that can be placed mid-air and are immediately mounted

### ISSUE THREAD

**Issue by gyrohero** [DonBruce64/MinecraftTransportSimulator#640]
The idea is to allow parachutes, but this may have some other applications as well.

On the JSON side, this could just be an additional parameter "mountOnPlacement". If it's true, then instead of getting the block the player is looking at when they right-click with a vehicle in hand, it will be placed at the player's position. And as long as that vehicle has a seat, the player will immediately be mounted in the first seat available.

For parachutes, this would be implemented as an engineless vehicle with high drag and no or limited control surfaces (depending on the type of parachute). Hang-gliders would be engineless vehicles with control surfaces.

Edit: an additional variable "dropWhenOnGround" could replicate having to pick the parachute up once the player has landed. Once the parachute contacts the ground, the player is dismounted and the parachute item drops as if it was shift-hit by a wrench.

**Comment by DonBruce64** [comment]
So, I'm gonna call this, as it should really be a different implementation than a normal vehicle.  However, this will also be a backburner behind other things due to time constraints and the fact it's just for parachutes, which other mods add.|

**Comment by gyrohero** [comment]
(And jetpacks)

**Comment by mylesbartlett72** [comment]
This is also useful for planes with pontoons, as those cannot be moved on land, but cannot be placed on water.  Maybe a similar implementation (but checks for water)

**Comment by DonBruce64** [comment]
So, after this sitting here for years, I'm going to close this ticket.  There are other mods that add parachutes, and the time it would take for me to create another entity in the code to do this just isn't what I want to spend time on now, or in the foreseeable future.

**Comment by boot2big** [comment]
_Well..._ Unfortunately taking on this PR myself would be beyond my scope of ability right now, but at least I'm modeling a contender for this actually! (I _swear_ this ticket only occured to me after starting work on it, and it's mostly because I don't want a MiB giant "jet" pack or a GTAO ugly frame jetpack.)

![image](https://user-images.githubusercontent.com/53581325/191145219-a2e99c85-378b-42bf-8cec-fe5b0b68b6c4.png)

I'll have this in the game within a couple days, and probably working by a few days (both estimated from this moment)

**Comment by boot2big** [comment]
As of this commit, the IVLabs Jetpack is in a mostly working state.
https://github.com/boot2big/immersive_vehicles_vanity/commit/b5fb3b5c5398849cc09fbec3910619d53eaa0a77
While having this feature is by no means a requirement (when placed, the jetpack will simply just fall to the ground and be usable from there) it would be slightly appreciated. No rush though, I'm aware progress is still being made to upgrade MTS to 1.16 rather than working on various requests and bugs.
