### ISSUE TITLE
[Enhancement] Even more light variables

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#66]
I know we have a bunch of light variables, but I think two more that would be useful would be a light variable that is always on, and/or one that turns on with the engine.

**Comment by DonBruce64** [comment]
While these are possible, why on earth would you need them?  I would think when the car is off you wouldn't want any lights on?

**Comment by DrprofLuigi** [comment]
Cyberpunk vehicles, and glowing UNU branding

If you can't see an UNU logo 24/7, that's a problem

**Comment by DonBruce64** [comment]
Well yeah, but lights won't do anything in the daytime, and seeing as how you don't want to leave your lights on when the car is off as the battery would die, I'm not sure why you can't just use the "Special" lights for your UNU logos and use the headlights for the main lights.

**Comment by DrprofLuigi** [comment]
What I'm thinking about is like neon glowing details that are always on (think tron). if that was tied to a special light, then it would have to be turned on manually, as opposed to 'always on' or 'on with the engine.'

**Comment by DonBruce64** [comment]
MTS automatically drains a bit of battery for all lights when they are on, so an always-on light would eventually kill your car.  If, however, you wanted a light separate from the headlights, that could be do-able.  In fact, you can technically do it now as there's a SpecialLights keybind for cars.  Those tend to go to emergency lights, but for a tron-like system you could bind it to that.  You could also bind it to a disco ball, because why the heck not?

**Comment by DrprofLuigi** [comment]
Well yeah, but I meant something that automatically turns on with the engine. So whenever the enigne is running, these lights are on. The battery wouldn't drain as the engine is running. It would be automatic, as opposed to the siren which would be manual.

**Comment by DonBruce64** [comment]
Yeah, that's not going to be a thing, simply because all lights take battery power, and I don't want to make them on-off automatically because dang-it, there has to be SOME ramifications for leaving your lights on!  Special lights should serve you just fine for non-headlight purposes, and even if they don't, nothing says you can't just hook the lights into the main headlight banks and use those.
