### ISSUE TITLE
Vehicle Destruction

### ISSUE THREAD

**Issue by conman180** [DonBruce64/MinecraftTransportSimulator#701]
Vehicles will explode and disappear when they crash. However, damage from guns will only destroy parts of the vehicle. Engines, props, etc. It would be nice for vehicles to be able to be destroyed completely from weapons.

**Comment by DonBruce64** [comment]
How would you recommend we handle this?  Because not all weapons are created equal.  You shouldn't be able to destroy a vehicle with a machine-gun, no matter how many rounds you put into it.  A tank shell, however, would do more damage, but not if it just hits the roof and misses all the critical parts.

**Comment by DonBruce64** [comment]
Closing due to no response from issuer for one month.
