### ISSUE TITLE
Allow animations to affect a part's placement slot

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#757]
Basically, allow the animation of a part to apply even if the part is not present, so the green 'slot' gets animated. If this is too much of a load, a minimum of the visibility variable making the slot disappear would be nice. That way different engine sizes can go in different part slots to activate dual exhaust for example, but the other engine slot disappears so you don't end up with two engines.

**Comment by DonBruce64** [comment]
Doing animations on holo-boxes will be nasty.  Especially since if you don't have either part in the slot, then you'll end up with double-colliding holoboxes where the player might not even know they can put a larger engine in due to the one box blocking the other.  Scanners will get confused because you'll have two boxes right next to one another without any parts in them.  Plus then you'll get a red/green state of two boxes if you're holding a part that's only valid for one of them.

For dual-exhausts, I'd much prefer that be handled during the particle re-vamp (with a visibility block based on fuel consumption).  Also, holoboxes *do* move, but only if put on a moving part.  They can't move with model animations like your tilt-cab because that's done in the model, and holo-boxes are rendered after the model in a funky static system because they're not part of the model, nor parts.  I could find a way to do such a thing, but TBH, the only times I've seen this be an issue is on your tilt-cab, and that setup is better handled by making the cab its own default-permanent part, and having all your collision boxes part of that guy, and letting it do the heavy lifting of moving them.  This would also fix the doors not lining up when tilted, as they do now.

So, while I agree with the thoughts behind your ticket, I honestly don't think it's the right way to go given MTS's architecture and system limitations.  Gonna hafta wontdo it.
