### ISSUE TITLE
Bug: penetrsting floor while dismounting

### ISSUE THREAD

**Issue by chj990707** [DonBruce64/MinecraftTransportSimulator#82]
When I dismount vehicles on 1 block thick floor, I sometimes penetrate and fall through the floor. Plus this happened in seaplanes too; dismounting instantly teleports me into deep water.

**Comment by DonBruce64** [comment]
When you dismount, do you move instantly to the dismount point, or do you move slightly up when you dismount?  Also, what direction are you being dismounted from the seat, and which seat are you dismounting?  I'm trying to figure out if that's the MC dismounting code or if it's the MTS dismounting code.

**Comment by chj990707** [comment]
Can't be sure; I should try to recreate the situation to answer. It seems not to happen all the time...

**Comment by DonBruce64** [comment]
I ask, because I *suspect* what is happening is the vehicle doesn't have a dismount point defined, so MTS tries to automatically find a dismount position.  However, it can't find a position, so it defaults to let MC dismount, and MC picks poorly like it usually does.  If it's MTS dismounting, you should be about 1-1.5 blocks to the left of the seat for seats on the left of the plane, and 1-1.5 blocks to the right for seats on the right side of the plane.  If you're going backwards and down, or just straight down, that's MC doing the dismounting.

**Comment by chj990707** [comment]
The dismounted position was always down if not straight down; I can confirm that.

**Comment by DonBruce64** [comment]
If you can re-produce it let me know.  I may need to re-classify this bug as a packard to add dismount positions for the planes to prevent this.

**Comment by DonBruce64** [comment]
Can confirm that this is indeed an issue with the dismount position.  MTS is trying to dismount the player to the side of the plane but they hit the wing, so instead it lets Minecraft take over.  When Minecraft takes over, it too can't find a good place, and so it just dismounts the player in-place, causing them to fall down.  Re-classifying this as a pack-based bug as that's what needs to be changed.

**Comment by DonBruce64** [comment]
Closed as of V12 of the pack.
