### ISSUE TITLE
Parts with windows

### ISSUE THREAD

**Issue by TheCactus27** [DonBruce64/MinecraftTransportSimulator#86]
Allow parts to have windows in them. Similar to vehicles, the amount of windows would be found in the part's .json file, so the mod knows how many windows to repair. Without this, the windows on the scout's roofs will just be purely decorative.

**Comment by DonBruce64** [comment]
The problem with this is that the number of broken windows is kept in the vehicle data as that's where all the windows are.  MTS doesn't know *which* windows are broken, as that would require parsing the model on the server, which is a no-no.  Because of that, it won't know if a part or vehicle window is broken, and won't react correctly when parts are removed.  This is too difficult for me to add without significant hackery, so I'm not going to do so.  If someone else wants to code it in I'll be more than happy to review and let it stand.
