### ISSUE TITLE
[ENHANCEMENT] Shift straight to neutral using MOD + SHIFTUP/DOWN (depending on if engine is in reverse or forward)

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#865]
Hypothetically, if one wanted to shift into neutral to coast without revving their engine via engine breaking, such a feat would be impossible with a manual car (or very very risky, as you'd have to shift through anywhere between three and six gears as fast as possible to avoid engine damage by overrevving)

**Comment by DonBruce64** [comment]
So, I can do this, but I can't assure it'll work properly all the time due to the fact shifting is coded to either be up or down, and not a specific gear selected.  So I can send off 6 downshift packets at once, but if they don't batch together then you'll end up with one perhaps being handled 1 second after the others, so you'll be in 1st gear for a little bit.

If, however, you want to *only* go to neutral and not auto-shift back into gear *from* neutral, I could see about coding a specific packet for that.  That work?

**Comment by boot2big** [comment]
Sounds good to me, being able to emergency neutral is better than nothing

**Comment by DonBruce64** [comment]
Implemented in V20.0.0.
