### ISSUE TITLE
[ENHANCEMENT/TWEAK] Right click on pump then vehicle instead of relying on proximity?

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#875]
Could prevent some confusion as to which vehicle you're fueling as it'd instead tell you something along the lines of this when clicking on a pump.
_"Now right click on a vehicle to fuel it."_

Alternatively if you didn't want to fuel a vehicle for some reason, you could just click the pump again to cancel it.

Jerrycan behavior would probably remain the same.

Should you walk 16 blocks away from the pump or manage to click on a vehicle that's 16 blocks away, it should simply cancel it with the same proximity message as right now, or a warning similar to ...
_You are too far from the pump, refuel canceled!_

**Comment by DonBruce64** [comment]
This would be tough.  Right now the pump can just check for all vehicles around it when you click.  If you do a double-click, then something needs to keep track of the pump clicked.  And it can't be the pump itself because then you're clicking on the vehicle the second time and the vehicle doesn't know nothing about *which* pump you might have clicked before.  And I can't store variable on the player because *Minecraft*.  It's why jumper cables and fuel hoses exist: they store the last-clicked variable.  While I understand the reasoning behind this, I'm going to have to flag it as a wontdo.
