### ISSUE TITLE
Translucent objects allergic to apply after

### ISSUE THREAD

**Issue by Ooferine** [DonBruce64/MinecraftTransportSimulator#884]
Any translucent model object will disappear when assigned an animation block with applyafter.

**Comment by DonBruce64** [comment]
This only happens when the translucent object is told to applyAfter a solid object.  Due to the fact they always render on a different pass, this is not possible.  However, I can see about caching the rotations during the rendering overhaul to allow for this.  As such, I'm marking it as an enhancement, but backburner.

**Comment by DonBruce64** [comment]
Fixed in V21.0.0.
