### ISSUE TITLE
Traffic Lights Continue To Flicker After Being Configured

### ISSUE THREAD

**Issue by OCEAN02** [DonBruce64/MinecraftTransportSimulator#906]
As title says, there is no way to stop traffic lights from flickering on latest build. Tested with both IV and MTS style signals.

![2021-08-15_14 10 05](https://user-images.githubusercontent.com/64695321/129489739-e624ad94-0c28-41d9-bb3a-8afdad4ab372.png)

![2021-08-15_14 10 38](https://user-images.githubusercontent.com/64695321/129489740-c89f9002-9360-4b7f-85cc-7c167e5bf00e.png)

**Comment by OCEAN02** [comment]
https://user-images.githubusercontent.com/64695321/129489904-6179a3a3-c746-4ca8-99a8-b9c7f375e39b.mp4

**Comment by DonBruce64** [comment]
This is a bug with the lights having old un-linked variants.  It's wholly the fault of the pack, not the code.  Flagging as a pack update.  I've already fixed this in the OCP, but haven't released a build as I'm looking to add a helicopter during my next release. 
 You can download the updated models from the link below and swap them in your jar if you want a fix before I get to updating the OCP.  Otherwise I'm afraid you'll have to wait.  Same with the UNU signals.

https://github.com/DonBruce64/MTSOfficialPack/tree/master/main/resources/assets/mtsofficialpack/objmodels/poles

**Comment by DonBruce64** [comment]
Fixed in V22 of the OCP.
