### ISSUE TITLE
Ground physics bug: vehicle moving despite parking brake being engaged...

### ISSUE THREAD

**Issue by PearlCGDoesYT** [DonBruce64/MinecraftTransportSimulator#93]
This sometimes happens but it does annoy me and when I park it in anywhere and it moves away from where I parked it, I know for damn sure that IRL vehicles don't do that unless the nut behind the wheel forgets to engage it

**Comment by PearlCGDoesYT** [comment]
Oh, I forgot to mention this, even if the parking brake is off and the vehicle is on flat ground this bug still does happen, I'll have screenshots up when I can

**Comment by DonBruce64** [comment]
How far do they move?  About 1 block?  Do they keep moving forever?

**Comment by PearlCGDoesYT** [comment]
Have not tested that yet but it does move around a block, I tested that in a single car garage and as soon it hit the wall it stopped, but moving forever... Unconfirmed as far as my testing goes

**Comment by PearlCGDoesYT** [comment]
And I'll test if it happens on the latest version

**Comment by DonBruce64** [comment]
If you could, that would be great.  I have seen cars move very slowly after having the parking brake applied due to them being very far out of sync from the server.  They should stop moving in about 5 seconds at the usual rate, but if they keep moving, then that's a problem.  Hard to tell if the garage case was a sync closer to the wall, or a runaway car.

**Comment by PearlCGDoesYT** [comment]
I'll see what I can reproduce

I'm doing the testing on a work in progress city that I'm building which also is in single player

I'll keep you posted

**Comment by Einsiedler98** [comment]
I had the same issue as the author. I created a flat parking space near the runway where I parked my plane and at some point it just started sliding away (towards positive Z in my case, which related to the vehicle sliding lateral to the left). The plane definitely slided more than one block, because I had to attach more blocks to the side in order to avoid it from falling down the platform. I then tried to build a one block height wall to "stop" the wheel, but as soon as it hits that block it glitched into the ground with that wheel.
Haven't tried to reproduce it, also not sure how because I cannot tell if its related to the parking brake at all, the type of vehicle or the ground material.

**Comment by PearlCGDoesYT** [comment]
> I had the same issue as the author. I created a flat parking space near the runway where I parked my plane and at some point it just started sliding away (towards positive Z in my case, which related to the vehicle sliding lateral to the left). The plane definitely slided more than one block, because I had to attach more blocks to the side in order to avoid it from falling down the platform. I then tried to build a one block height wall to "stop" the wheel, but as soon as it hits that block it glitched into the ground with that wheel.
> Haven't tried to reproduce it, also not sure how because I cannot tell if its related to the parking brake at all, the type of vehicle or the ground material.

I'll test that definitely

**Comment by DonBruce64** [comment]
Had this happen to me in the dev system shortly after spawning in a Trimotor with no engines.  Clearly, something is not right here.  Pretty sure it's related to the ground physics, as those are the only forces that are acting on it at that time.  Rolling this bug into #83.
