### ISSUE TITLE
[Request] validSubTypes to allow variant-specific parts to go onto this vehicle

### ISSUE THREAD

**Issue by LauraDarkez** [DonBruce64/MinecraftTransportSimulator#933]
validSubNames – A list of subNames this part can go on. If included, this part will only be allowed to go on the specified definition sub-name variants. Used to allow for variant-specific configurations, such as police variants of cars.

validSubTypes – A list of subNames of the part that can go onto this vehicle. If included, the part will only be allowed if its subName matches what is provided in the list. If used in conjunction with "validSubNames", it will allow only specific part variants to go on specific vehicle variants. Useful for variant specific configurations, such as keeping blue or red gyrophares off of towtrucks and snowplows that take yellow/orange gyrophares

**Comment by boot2big** [comment]
What-do if someone repaints with the paint gun? Sounds like a great idea to me, just wondering

**Comment by LauraDarkez** [comment]
then if you take it off it wont go back on. unless don somehow codes in a blocker to prevent you from painting something to an invalid subName

**Comment by DonBruce64** [comment]
Eh, Franz and I talked about this with his variant typing where he has police cars where the part slots are only active for the police livery.  We agreed that while it might be slightly cheeky to re-paint your car with the lights on it, it's not *techinally* against normal IRL stuff.  Just look at all the old Crown Vics with those old hand-held lights and bull-bars.

However, I'm gonna wontdo this ticket, purely because we already have something that locks parts to specific slots and vice-versa: the old customTypes.
