### ISSUE TITLE
Cars go missing when driver disconnects.

### ISSUE THREAD

**Issue by 77RaZe77** [DonBruce64/MinecraftTransportSimulator#934]
I use version Immersive + Vehicles-1.12.2-20.1.0, the problem with the disappearance of vehicles was solved, but not 100%. They still disappear on the server, and here's how: when a player drives a car and abruptly leaves the game, it disappears, even if the player stopped on it, but immediately left the game, it disappears. And here's the question: where do they go to? is it worth worrying about the fact that they actually stand somewhere?

**Comment by DonBruce64** [comment]
Is this ONLY when they leave while they are in the car?

**Comment by GlobalHive** [comment]
Can confirm that

If you disconnect while sitting in a car, it disappears.
Sometimes it respawns on rejoin sometimes not

Fix idea: Dismount on disconnect

**Comment by DonBruce64** [comment]
Yeah, that's likely Minecraft entity syncing.  I don't know I can dismount on disconnect, as I don't nessicarally get a disconnect request if they crash or their computer freezes.  What I CAN do is make a fake entity that they ride that's *not* the car so when they disconnect they just make that go away rather than the car itself.  Will also work nicely with sit-able decor blocks.  This will take a bit to implement, but is a better way to handle entity riding and may allow for complete entity abstraction in the future.

**Comment by GlobalHive** [comment]
Well i don't know exactly how to do it, but google (Yeah i know google lies sometimes...) says: Get on disconnect the ridden entity (Car) and then "Eject" the Rider -> [Here](https://www.spigotmc.org/threads/dismount-on-disconnect.462569/)

**Comment by DonBruce64** [comment]
Fixed in V21.2.0.
