### ISSUE TITLE
Planes wont take off unless they fall down at least 1 block

### ISSUE THREAD

**Issue by adamvelvick** [DonBruce64/MinecraftTransportSimulator#970]
When I try to fly any form of plane, MC-172, Vulcanair etc, as I take off and try to pull up, the plane glitches a lot, as if it's trying to get into the air, but it won't take off, it's almost as if it's stuck to the ground. I have to ramp the plane off the edge of a block for it to want to take off. 

If the problem can be solved easily, any help would be appreciated, everyone on my server is having the same issue ever since we updated to IV 20.1.0 and MTS v22.

Here's a video of what happens: https://youtu.be/zLd4u1pELHE

Edit: The eclipse works fine as it can achieve higher speeds quicker, seems to be turboprop planes only

**Comment by DonBruce64** [comment]
Odd, do you happen to know which exact version this happened in?  What were you running before and did that work?

**Comment by Jachdich** [comment]
@DonBruce64 as far as my testing goes, [that commit](https://github.com/DonBruce64/MinecraftTransportSimulator/commit/75295f17582801b082622af29c844ba998052b28) solved the issue completely. I patched the code into v20.1.0 so that people who play on a server but don't have planes don't have to update right away, would this cause any significant issues or is it okay until we can get everyone to update MTS versions?

**Comment by DonBruce64** [comment]
That should be just fine.  That's a fairly minor physics addition.  You could conceivably install it just on the server, though you'd get some funny rubberbanding during takeoff due to syncing code trying to lift the plane on the client to match the server.  For sure though it's compatible with older versions like that.

**Comment by adamvelvick** [comment]
As @Jachdich has said, this has solved all our problems, so thanks :)
Await his response on your question, once he finally wakes up haha

Anyway thanks for that fix and for taking the time and effort to make this mod in the first place, we all really enjoy it!

**Comment by DonBruce64** [comment]
Fixed in V20.4.0.

**Comment by DonBruce64** [comment]
And you're welcome!  I'm just happy people are using the mod.  Though I really do wish I could get it updated to higher MC faster.  Updates have always been painful, and this one is far worse than the others now that I have to juggle it, and features and these old bugs.

**Comment by Jachdich** [comment]
@DonBruce64 
> Also, patching code? Sure I can't interest you in a position with IV Labs coding divisions? ;)

Well I am not the *best* at programming but I might be able to help out here and there with a few things, and I would love to contribute to my favourite mc mod :)

**Comment by DonBruce64** [comment]
@Jachdich well, if you've got time I'd appreciate any help I can get.  There's always little stuff to be done besides the main update stuff, so help with that lets me focus on the big items.  If you've got time, hit me up on the Discord.  That's where I stay most evenings and is the best way to get ahold of me.  Looking forward to it!
