### ISSUE TITLE
Request: Dual engine setup maybe possible on ground vehicles???

### ISSUE THREAD

**Issue by PearlCGDoesYT** [DonBruce64/MinecraftTransportSimulator#98]
I have mentioned this on the discord, but some people might want a dual engine car, but the person who modeled a vehicle will have to put in extra work so 2 engines can be put into a car or some might want the option to place the trunk in the front and the engine in the back or vise versa without having to grab an extra of the same vehicle from the creative menu and making a total mess of the menu

I am willing to put in the extra work so most of my vehicles can have such a thing

**Comment by DonBruce64** [comment]
The problem with this is that all vehicles, with the exception of planes, send all their engine commands (start/stop, get RPM, etc) to engine # 1.  Because of this, having two engines means that you could have an engine in the # 2 bay that will never get the start signal because everything is set to the first bay.

That's not saying it can't be done.  But that is saying it would be a lot of minor changes to do so.  You are welcome to submit a Pull Request for such a change if you wish, but I myself will not be adding this.  I say this to differentiate it from transmissions being separate, which is not only something I will not do, but also something that if done, I will not add to the MTS code.

**Comment by PearlCGDoesYT** [comment]
I'll figure something out, but for now, I understand cause that will require such a major change so that both can start up and shift at the same time, and I have already forked IV/MTS so I can figure it out without messing up the main code and maybe have a merge when it's working 100%

**Comment by DonBruce64** [comment]
It's a lot easier if you only have one engine in the vehicle at any time.  Then they won't be binding.  You could even have two automatics, and in theory they'd do just fine as both would be independent.  Two manuals though, especially two with different gear ratios, could get messy fast.

**Comment by PearlCGDoesYT** [comment]
Yeah, then it would have to be limited if you had one engine with one set specific manual ratios, then the other engine has to be the exact same engine with the same ratios....

But for now maybe have it so when you place the engine in the rear, you only can place a "crate" in the front, same with the other way around but that would take some time to code in
